// @sprinta/api — Supabase servis katmanı

export { createSupabaseClient } from './services/supabase'
export { createAuthService, RegisterSchema, LoginSchema } from './services/auth'
export type { RegisterInput, LoginInput } from './services/auth'
export { createPerformancePipeline } from './services/performancePipeline'
export { createDiagnosticService } from './services/diagnosticService'
export type { SaveDiagnosticParams } from './services/diagnosticService'
export { createBadgeService } from './services/badgeService'
export type { Badge, StudentStats } from './services/badgeService'
export { createStreakService } from './services/streakService'
export { PurchasesService } from './services/purchases'
export { createContentService } from './services/contentService'
export { createProgramService } from './services/programService'
export type { ExamProgram, StudentProgram, Phase, DailyTask } from './services/programService'
export { createAICoachService } from './services/aiCoachService'
export type { AICoachMode, ChatMessage as AIChatMessage, AICoachResponse } from './services/aiCoachService'
export { createLeaderboardService } from './services/leaderboardService'
export type { LeaderboardEntry, Challenge, ChallengeType, LeaderboardSort } from './services/leaderboardService'
export { createChunkRsvpService } from './services/chunkRsvpService'
export type { WPMDataPoint } from './services/chunkRsvpService'
export { createFlowReadingService } from './services/flowReadingService'
export type { FlowReadingMetrics } from './services/flowReadingService'
export { createUserContentService, analyzeContent, suggestChunks } from './services/userContentService'
export type { UserContent, UserContentChunk, ContentAnalysis, SuggestedChunk } from './services/userContentService'
export type { Database } from './types/database'
export { createStarService, calculateStars } from './services/starService'
export type { GamificationState, DailyProgress, StarStreak, StarTotalStats, StarMilestone } from './services/starService'
