-- ================================================================
-- 028_library_content.sql
-- Metin Kütüphanesi içerik seed — 52 makale
-- LGS(10) · TYT(12) · ALES(10) · KPSS(10) · General(10)
-- ================================================================

DO $$
DECLARE
  t1  uuid; t2  uuid; t3  uuid; t4  uuid; t5  uuid;
  t6  uuid; t7  uuid; t8  uuid; t9  uuid; t10 uuid;
  t11 uuid; t12 uuid; t13 uuid; t14 uuid; t15 uuid;
  t16 uuid; t17 uuid; t18 uuid; t19 uuid; t20 uuid;
  t21 uuid; t22 uuid; t23 uuid; t24 uuid; t25 uuid;
  t26 uuid; t27 uuid; t28 uuid; t29 uuid; t30 uuid;
  t31 uuid; t32 uuid; t33 uuid; t34 uuid; t35 uuid;
  t36 uuid; t37 uuid; t38 uuid; t39 uuid; t40 uuid;
  t41 uuid; t42 uuid; t43 uuid; t44 uuid; t45 uuid;
  t46 uuid; t47 uuid; t48 uuid; t49 uuid; t50 uuid;
  t51 uuid; t52 uuid;
BEGIN

-- Zaten içerik varsa tekrar ekleme
IF (SELECT COUNT(*) FROM text_library) > 5 THEN RETURN; END IF;

-- ══════════════════════════════════════════════════════════════
-- LGS METİNLERİ (10 adet) — Difficulty 1-3
-- ══════════════════════════════════════════════════════════════

INSERT INTO text_library (id, title, category, exam_type, difficulty, word_count, estimated_read_time, body, tags, status)
VALUES
  (gen_random_uuid(), 'Hücrenin Yapısı ve Organelleri', 'Fen Bilimleri', 'LGS', 2, 320, 3,
E'Hücre, tüm canlıların yapı ve işlev birimidir. Gözle görülemeyen bu küçük yapılar, yaşamın temel taşlarını oluştururlar. Bilim insanları hücreleri ilk kez mikroskobun icadından sonra keşfetmiş ve zamanla hücre teorisini geliştirmişlerdir. Bu teoriye göre tüm canlılar hücrelerden oluşmakta, yeni hücreler mevcut hücrelerden meydana gelmekte ve yaşamsal faaliyetler hücrede gerçekleşmektedir.\n\nHücrenin dışını çevreleyen hücre zarı, maddelerin hücreye girip çıkmasını düzenler. Seçici geçirgen özelliği sayesinde faydalı maddeleri içeri alırken zararlı atıkları dışarı iter. Hücre zarının içinde sitoplazma bulunur; bu jel benzeri sıvı ortamda organeller yüzerler.\n\nÇekirdek, hücrenin kontrol merkezidir. DNA moleküllerini barındıran çekirdek, hücrenin büyümesini, bölünmesini ve işlevlerini yönetir. Mitokondri ise hücrenin enerji santralidir; besinlerden elde edilen enerjiyi ATP molekülüne dönüştürür. Kloroplastlar bitkiye özgü organellerdir ve fotosentez yaparak güneş enerjisini kimyasal enerjiye çevirirler. Ribozomlar protein sentezinin gerçekleştiği küçük yapılardır; hücrenin her yanında bulunabilirler.',
  ARRAY['hücre','organel','biyoloji','LGS'], 'published'),

  (gen_random_uuid(), 'Türkiye''nin Coğrafi Bölgeleri', 'Sosyal Bilgiler', 'LGS', 2, 290, 3,
E'Türkiye, yedi coğrafi bölgeye ayrılmaktadır: Karadeniz, Marmara, Ege, Akdeniz, İç Anadolu, Doğu Anadolu ve Güneydoğu Anadolu. Bu bölgeler iklim, bitki örtüsü, nüfus yoğunluğu ve ekonomik faaliyetler bakımından birbirinden belirgin biçimde farklılaşır.\n\nEge ve Akdeniz bölgeleri Akdeniz iklimine sahip olup kışları ılıman ve yağışlı, yazları sıcak ve kurudur. Bu iklim zeytinyağı, narenciye ve üzüm üretimine elverişlidir. Karadeniz bölgesi ise her mevsim yağışlı bir iklime sahiptir; fındık, çay ve mısır bu bölgenin başlıca tarım ürünleridir.\n\nİç Anadolu, step ikliminin hâkim olduğu geniş bir platodur. Tahıl tarımı ve hayvancılık burada yaygındır. Doğu Anadolu bölgesi karasal iklimin en sert yaşandığı yerdir; kışlar çok soğuk ve karlı geçer. Güneydoğu Anadolu ise sıcak ve kurak yapısıyla pamuk ve antep fıstığı tarımına uygundur. Marmara bölgesi sanayinin ve nüfusun en yoğun olduğu bölgedir; İstanbul bu bölgenin merkezi konumundadır.',
  ARRAY['coğrafya','bölgeler','Türkiye','LGS'], 'published'),

  (gen_random_uuid(), 'Işığın Kırılması ve Optik Olaylar', 'Fen Bilimleri', 'LGS', 3, 305, 3,
E'Işık, bir ortamdan diğerine geçerken yön değiştirirse buna kırılma denir. Örneğin havadan suya geçen bir ışık demeti, iki ortam arasındaki sınırda kırılarak ilerler. Bu olayın temelinde ışığın farklı ortamlardaki hızları arasındaki fark yatmaktadır; ışık yoğun ortamlarda daha yavaş hareket eder.\n\nKırılma açısı ve gelme açısı arasındaki ilişki Snell yasasıyla ifade edilir. Buna göre ışık ışının yoğun ortamdan seyrek ortama geçerken normale göre uzaklaştığı, seyrek ortamdan yoğun ortama geçerken ise normale yaklaştığı görülür. Gökkuşağı, yağmur damlalarının güneş ışığını kırmasıyla oluşan güzel bir doğa olayıdır.\n\nYansıma ise ışığın bir yüzeyle karşılaşınca geri dönmesi olayıdır. Düzgün yüzeylerde düzenli yansıma, pürüzlü yüzeylerde ise dağınık yansıma gözlemlenir. Aynalar düzgün yansımanın en yaygın örneğidir. Çukur ve tümsek aynalar ise ışık demetlerini odaklayarak ya da yayarak büyütme veya küçültme etkileri oluştururlar; bu özellikten teleskopta, farklarda ve güneş kolektörlerinde yararlanılır.',
  ARRAY['optik','ışık','fizik','LGS'], 'published'),

  (gen_random_uuid(), 'Osmanlı''nın Yükseliş Dönemi', 'Tarih', 'LGS', 2, 280, 3,
E'Osmanlı Devleti, 1299 yılında Osman Bey tarafından kurulan küçük bir beylikten zamanla dünyanın en güçlü imparatorluklarından birine dönüşmüştür. Yükseliş döneminin en önemli hükümdarı hiç kuşkusuz Fatih Sultan Mehmet''tir. Onun 1453''te İstanbul''u fethiyle Ortaçağ kapanmış ve Yeniçağ başlamıştır.\n\nYavuz Sultan Selim döneminde Osmanlı, Mısır''ı ve Hicaz''ı topraklarına katarak hilafetin sahibi oldu. Bu gelişme Osmanlı''ya İslam dünyasının lideri konumunu kazandırdı. Kanuni Sultan Süleyman ise hem siyasi hem de hukuki alanda yaptığı düzenlemelerle adını tarihe altın harflerle yazdırmıştır. "Kanuni" unvanı da bu dönemin yarattığı hukuki düzenin bir simgesidir.\n\nYükseliş döneminde devşirme sistemi Osmanlı ordusunu güçlendirmiş; yeniçeri ocakları savaş meydanlarında üstün başarılar elde etmiştir. Toprak kullanım sistemleri olan tımar ve dirlik düzenlemeleri devletin ekonomisini canlı tutarken çeşitli etnik ve dini toplulukların millet sistemiyle bir arada yaşamasına olanak tanınmıştır.',
  ARRAY['osmanlı','tarih','LGS'], 'published'),

  (gen_random_uuid(), 'Türkçede Sözcük Türleri', 'Türkçe', 'LGS', 1, 260, 2,
E'Türkçede sözcükler anlamlarına ve cümlede üstlendikleri işlevlere göre sekiz temel türe ayrılır: isim, sıfat, zamir, zarf, fiil, edat, bağlaç ve ünlem. Bu sınıflandırma dilin düzenli ve anlaşılır kullanılmasının temelini oluşturur.\n\nİsimler varlıkları ve kavramları karşılayan sözcüklerdir; "taş, sevgi, okul, hava" gibi. Sıfatlar isimleri niteleyen ya da belirten sözcüklerdir: "güzel çiçek, üç kitap, bu ev". Zamirler isimlerin yerini tutarlar: "ben, sen, o, biz, onlar". Zarflar ise fiilleri, sıfatları ve diğer zarfları nitelerler: "hızlı koştu, çok güzel".\n\nFiiller eylemleri, hareketleri ve durumları bildiren sözcüklerdir; Türkçede fiil çekimi son derece zengindir. Edatlar tek başlarına anlam taşımayan ama cümlede anlam ilişkisi kuran sözcüklerdir: "için, ile, gibi, kadar". Bağlaçlar sözcükleri ya da cümleleri birbirine bağlarlar: "ve, ama, fakat, ya da". Ünlemler duyguları ve seslenimleri ifade ederler: "ah, of, hey, bravo". Bu sözcük türlerini iyi kavramak, hem yazma hem de okuma becerilerini güçlendirir.',
  ARRAY['gramer','sözcük türleri','Türkçe','LGS'], 'published'),

  (gen_random_uuid(), 'Besinlerin Sindirimi ve Emilimi', 'Fen Bilimleri', 'LGS', 2, 310, 3,
E'Sindirim sistemi, vücuda alınan besinleri parçalayarak hücrelerin kullanabileceği küçük moleküllere dönüştüren karmaşık bir organlardır bütünüdür. Sindirim ağızdan başlar; dişler besinleri fiziksel olarak parçalarken tükürük içindeki enzimler nişastayı kimyasal olarak sindirmeye başlar.\n\nYemek borusundan geçen besinler mideye ulaşır. Midede mide özsuyu, özellikle proteinleri parçalayan enzimler içerir. Kuvvetli asit ortamı zararlı bakterileri de yok eder. Mideden çıkan yarı sindirilmiş besinler ince bağırsağa geçer. İnce bağırsak sindirim ve emilimin büyük çoğunluğunun gerçekleştiği yerdir.\n\nKaraciğer salgıladığı safra ile yağları parçalamada yardımcı olurken pankreas enzim salgılayarak protein, yağ ve karbonhidrat sindirimini tamamlar. İnce bağırsağın iç yüzeyindeki parmak benzeri çıkıntılara villüs denir; bu yapılar emilim yüzeyini büyük ölçüde artırır. Sindirilmiş besinler buradan kana karışarak tüm vücuda taşınır. Sindirilemeyen atıklar kalın bağırsağa geçer ve su emilimi sonrası dışarı atılır.',
  ARRAY['sindirim','biyoloji','LGS'], 'published'),

  (gen_random_uuid(), 'Elektrik ve Manyetizma', 'Fen Bilimleri', 'LGS', 3, 295, 3,
E'Elektrik, yüklü parçacıkların hareketiyle ortaya çıkan bir enerji biçimidir. Atomun çekirdeği çevresinde dönen elektronlar negatif yüklüdür; bu elektronların bir iletken üzerinden akması elektrik akımını oluşturur. Elektrik akımının birimi amperdir ve bu akımı üreten gerilim farkının birimi ise volttur.\n\nManyetizma ise mıknatısların ve elektrik akımının çevresinde oluşan kuvvet alanlarıyla ilgilidir. Her mıknatısın kuzey ve güney olmak üzere iki kutbu bulunur; aynı kutuplar birbirini iterken zıt kutuplar birbirini çeker. Dünya''nın da kendi manyetik alanı vardır ve pusulalar bu alan sayesinde çalışır.\n\nElektromanyetizma, elektrik ve manyetizmanın birbirini etkilediği ve birbirine dönüşebildiği kapsamlı bir konu alanıdır. Bir elektrik akımının çevresinde manyetik alan oluşması bu ilişkinin temelini oluşturur. Değişen bir manyetik alanın ise elektrik akımı üretebilmesi elektrik jeneratörlerinin çalışma prensibini oluşturur. Günümüzde kullandığımız elektrik motorları, jeneratörler ve transformatörler bu prensibe dayanmaktadır.',
  ARRAY['elektrik','manyetizma','fizik','LGS'], 'published'),

  (gen_random_uuid(), 'Ekosistem ve Biyoçeşitlilik', 'Fen Bilimleri', 'LGS', 2, 280, 3,
E'Ekosistem, bir bölgede yaşayan tüm canlı organizmaların birbirleriyle ve cansız çevreleriyle oluşturdukları karmaşık sistemi tanımlar. Ormanlar, mercan resifleri, çöller ve sulak alanlar birer ekosisteme örnektir. Her ekosistemin kendine özgü iklim koşulları, bitki örtüsü ve hayvan toplulukları bulunur.\n\nEkosistemlerin sağlıklı işleyişi için biyoçeşitlilik kritik öneme sahiptir. Biyoçeşitlilik, bir bölgede yaşayan tür sayısı ve bu türlerin genetik farklılığıdır. Yüksek biyoçeşitlilik ekosistemlere esneklik kazandırır; hastalık veya doğal afet durumunda sistem kendini daha kolay onarabilir.\n\nBeslenme ilişkileri ekosistemde enerji akışını sağlar. Üreticiler (bitkiler) güneş enerjisini kimyasal enerjiye dönüştürürler. Birincil tüketiciler bitkilerle beslenen otçul hayvanlardır. İkincil tüketiciler ise otçullarla beslenen etçillerdir. Ayrıştırıcılar ölü organik maddeleri minerallere dönüştürerek besinlerin döngüsünü tamamlar. İnsan faaliyetleri bu hassas dengeyi bozabilmekte; ormansızlaşma ve kirlilik pek çok türü yok oluşun eşiğine getirmektedir.',
  ARRAY['ekosistem','biyoçeşitlilik','çevre','LGS'], 'published'),

  (gen_random_uuid(), 'Anadolu Medeniyetleri', 'Tarih', 'LGS', 2, 270, 3,
E'Anadolu, binlerce yıl boyunca pek çok büyük uygarlığa ev sahipliği yapmıştır. Tarih öncesi dönemden günümüze uzanan bu köklü geçmiş, Anadolu''yu "Medeniyetlerin Beşiği" olarak adlandırmamızı sağlar.\n\nM.Ö. 2000''li yıllarda Hitit İmparatorluğu Orta Anadolu''da kurulmuştur. Hititler demir işleme tekniklerini geliştirmiş ve kendi yazı sistemlerini oluşturmuşlardır. Dünyanın bilinen ilk barış antlaşması olan Kadeş Antlaşması Hititler ile Mısır arasında imzalanmıştır. Hititlerin yıkılmasının ardından Frigya, Lidya ve Urartu krallıkları Anadolu''da hâkimiyet kurmuşlardır.\n\nM.Ö. 334''te Büyük İskender Anadolu''yu fethetti ve Hellenistik dönem başladı. Roma hâkimiyeti döneminde Efes, Bergama ve Antakya gibi şehirler Akdeniz dünyasının önemli merkezleri hâline geldi. Bizans döneminde Anadolu Hristiyanlığın kalbi oldu. 1071 Malazgirt zaferinin ardından Türk boylarının Anadolu''ya yerleşmesiyle birlikte Türk-İslam medeniyetinin temelleri atıldı.',
  ARRAY['tarih','Anadolu','medeniyet','LGS'], 'published'),

  (gen_random_uuid(), 'Demokrasi ve Temel Haklar', 'Vatandaşlık', 'LGS', 2, 265, 3,
E'Demokrasi, halkın kendi kendini yönettiği ya da seçtiği temsilciler aracılığıyla yönetildiği bir sistem olarak tanımlanabilir. Antik Yunan''ın Atina şehrinde M.Ö. 5. yüzyılda ilk örnekleri görülen demokrasi, günümüzde dünyanın pek çok ülkesinde benimsenmiştir.\n\nTemsili demokrasilerde vatandaşlar belirli aralıklarla yapılan seçimlerle temsilcilerini belirler. Yasamayı (yasa yapmayı), yürütmeyi (yasaları uygulamayı) ve yargıyı (adaleti dağıtmayı) birbirinden bağımsız kurumların üstlenmesi "kuvvetler ayrılığı" ilkesini oluşturur. Bu ilke, iktidarın tek elde toplanmasını önler.\n\nDemokrasinin vazgeçilmez koşulu temel hak ve özgürlüklerin güvence altına alınmasıdır. İfade özgürlüğü, basın özgürlüğü, toplanma hakkı ve adil yargılanma hakkı bu temel güvenceler arasında sayılabilir. Türkiye Cumhuriyeti Anayasası bu hakları güvence altına almış olup her vatandaş bu haklardan eşit biçimde yararlanma hakkına sahiptir.',
  ARRAY['demokrasi','vatandaşlık','hukuk','LGS'], 'published');

-- ══════════════════════════════════════════════════════════════
-- TYT METİNLERİ (12 adet) — Difficulty 2-4
-- ══════════════════════════════════════════════════════════════

INSERT INTO text_library (id, title, category, exam_type, difficulty, word_count, estimated_read_time, body, tags, status)
VALUES
  (gen_random_uuid(), 'Evrenin Yapısı ve Kozmoloji', 'Fizik', 'TYT', 3, 330, 4,
E'Evren, yaklaşık 13,8 milyar yıl önce gerçekleşen Büyük Patlama ile başladığı düşünülen muazzam bir varlık alanıdır. Bu patlamanın ardından son derece yoğun ve sıcak olan madde hızla genişlemiş ve soğuyarak bugünkü yapısını oluşturmuştur. Modern kozmoloji, bu sürecin matematiksel modellerini geliştirerek evrenin kökenini ve evrimini anlamamızı sağlamaktadır.\n\nEvrende yaklaşık iki trilyon galaksi bulunmaktadır. Galaksiler, milyarlarca yıldız ve bunları bir arada tutan karanlık maddeden oluşmuş devasa sistemlerdir. Samanyolu galaksimiz yaklaşık 200-400 milyar yıldız barındırır ve Güneş sistemi bu galaksinin kenarlarından birinde yer alır. Galaksiler küme ve süper küme adı verilen daha büyük yapılar oluşturmaktadır.\n\nÇağdaş astronominin en büyük gizemlerinden biri karanlık madde ve karanlık enerjidir. Gözlemlenebilir madde evrenin yalnızca yüzde beşini oluşturmaktadır; geri kalanı bilinmeyen karanlık madde ve karanlık enerjiden ibarettir. Karanlık enerji evrenin genişlemesini hızlandırmakta olup bu hız giderek artmaktadır. Evrenin geleceği; Büyük Çöküş, Büyük Dondurma ya da Büyük Yırtılma gibi farklı senaryolarla tartışılmaktadır.',
  ARRAY['evren','kozmoloji','fizik','TYT'], 'published'),

  (gen_random_uuid(), 'DNA''nın Keşfi ve Genetik Devrim', 'Biyoloji', 'TYT', 3, 340, 4,
E'1953 yılında James Watson ve Francis Crick''in DNA''nın çift sarmal yapısını keşfetmesi, biyoloji tarihinin dönüm noktalarından birini oluşturmuştur. Bu keşif; Rosa Franklin''in X-ışını kırınım görüntüleri gibi önceki çalışmaların üzerine inşa edilmiştir ve genetik bilimini büyük ölçüde ilerletti.\n\nDNA (deoksiribonükleik asit) dört nükleotid bazı içerir: adenin, timin, guanin ve sitozin. Bu bazların dizilişi genetik şifreyi oluşturur. Gen ise belirli bir proteini kodlayan DNA dizisidir. Ribozomlar bu bilgiyi okuyarak aminoasitleri bir araya getirir ve proteini sentezler. Proteinler vücudun yapı taşları ve biyokimyasal süreçlerin yöneticileri olduğundan bu süreç hayatın sürdürülmesi açısından kritiktir.\n\nGenetik devrimin pratik yansımaları son derece geniştir. Gen mühendisliği yöntemiyle insülin üreten bakteri hücreleri elde edilebilmektedir. CRISPR-Cas9 teknolojisi DNA''nın istenilen noktasında değişiklik yapmaya olanak tanımaktadır. Kanser tedavisinde tümörün genetik profilini analiz eden kişiselleştirilmiş tıp yaklaşımları geliştirmektedir. Adli tıpta DNA parmak izi suçluların tespitinde belirleyici rol oynamaktadır.',
  ARRAY['DNA','genetik','biyoloji','TYT'], 'published'),

  (gen_random_uuid(), 'Termodinamiğin Yasaları', 'Fizik', 'TYT', 4, 315, 4,
E'Termodinamik, ısı ve iş arasındaki ilişkileri inceleyen fizik dalıdır. Birinci Yasa enerjinin korunumunu ifade eder: enerji yoktan var edilemez veya yok edilemez, yalnızca bir biçimden diğerine dönüştürülebilir. Bu yasa, bir ısı makinesinin yaptığı işin ve ortama verdiği ısının toplamının aldığı ısıya eşit olduğunu söyler.\n\nİkinci Yasa ise doğal süreçlerin yönünü belirler. Entropi —bir sistemin düzensizlik ölçüsü— izole bir sistemde her zaman artar ya da en kötü ihtimalle sabit kalır. Bu yasa, ısının soğuktan sıcağa kendiliğinden akmadığını ve mükemmel verimli bir makinenin gerçekleştirilemeyeceğini ortaya koyar. Entropi kavramı evrenin genel bir düzensizliğe doğru aktığını da öngörür.\n\nÜçüncü Yasa ise mutlak sıfır sıcaklığına (−273,15 °C) ulaşılmasının mümkün olmadığını ifade eder. Mutlak sıfırda atomik hareketin durması beklenir, ancak kuantum mekaniği sıfır nokta enerjisinin her zaman var olduğunu gösterir. Bu yasalar buhar makinelerinden buzdolabına, güç santrallerinden uzay araçlarına pek çok teknolojik sistemin tasarımında temel alınmaktadır.',
  ARRAY['termodinamik','fizik','enerji','TYT'], 'published'),

  (gen_random_uuid(), 'Organik Kimya Temelleri', 'Kimya', 'TYT', 4, 325, 4,
E'Organik kimya, karbon bileşiklerini inceleyen kimya dalıdır. Karbonun dört elektron bağı kurabilme özelliği, zincirleme ve halkalı yapıda milyonlarca farklı bileşiğin oluşmasına olanak tanır. Yaşayan organizmaların temel yapı taşları olan proteinler, karbonhidratlar, yağlar ve nükleik asitler birer organik bileşiktir.\n\nAlkanlar, sadece tekli C-C ve C-H bağları içeren doymuş hidrokarbonlardır. Metan, etan, propan ve bütan bilinen alkanlara örnektir. Alkenler ise en az bir çift bağ içerirken alkinler üçlü bağ barındırır. Aromatik bileşikler benzenden türeyen özel halkalı yapılardır ve kararlılıklarıyla dikkat çekerler.\n\nFonksiyonel gruplar, organik bileşiklerin kimyasal özelliklerini büyük ölçüde belirler. Alkol grubu (-OH) suyla karışabilirliği artırırken karboksil grubu (-COOH) asilik kazandırır. Amin grubu (-NH2) bazik özelliklere yol açar. Polimerizasyon sayesinde basit monomer birimler birleşerek lastik, plastik ve sentetik elyaf gibi günlük hayatta yaygın kullanılan malzemeleri oluşturur.',
  ARRAY['organik kimya','karbon','TYT'], 'published'),

  (gen_random_uuid(), 'Sinir Sistemi ve Nöronlar', 'Biyoloji', 'TYT', 3, 300, 3,
E'Sinir sistemi, vücuttaki tüm faaliyetleri koordine eden ve çevreyle iletişimi sağlayan karmaşık bir ağdır. İki temel bölümden oluşur: Merkezi Sinir Sistemi (beyin ve omurilik) ve Periferik Sinir Sistemi (vücuda yayılan sinir ağı). Bu iki sistem birlikte çalışarak yaşamsal işlevleri düzenler.\n\nNöron, sinir sisteminin temel yapı ve işlev birimidir. Her nöron; hücre gövdesi, akson ve dendritlerden oluşur. Dendritler diğer nöronlardan gelen sinyalleri alırken akson bu sinyali ileriye taşır. Nöronlar arasındaki bağlantı noktalarına sinaps denir; sinyaller burada nörotransmitter adı verilen kimyasal maddeler aracılığıyla iletilir.\n\nBeyin yaklaşık 86 milyar nörondan oluşmakta ve sürekli aktif olmaktadır. Serebral korteks düşünme, konuşma ve planlama gibi yüksek düzey işlevleri yönetirken serebellum denge ve motor koordinasyonu sağlar. Beyin sapı ise uyku, solunum ve kalp atışı gibi otomatik işlevleri kontrol eder. Nörobilimdeki son gelişmeler, beynin stres veya öğrenme gibi deneyimler sonucu yapısal olarak yeniden şekillenebildiğini (nöroplastisite) ortaya koymuştur.',
  ARRAY['sinir sistemi','nöron','biyoloji','TYT'], 'published'),

  (gen_random_uuid(), 'Cumhuriyet Dönemi Türk Şiiri', 'Edebiyat', 'TYT', 3, 310, 3,
E'Cumhuriyet''in ilanıyla birlikte Türk şiiri de köklü bir dönüşüm sürecine girmiştir. Milli mücadele yıllarının coşkusunu yansıtan şiirler yerini zamanla toplumsal sorunları ele alan, bireyin iç dünyasını derinlemesine araştıran eserlere bırakmıştır.\n\nNazım Hikmet, serbest ölçü ve siyasi içerikli şiirleriyle Türk şiirini yeniden biçimlendirmiştir. "İnsan Manzaraları" adlı uzun manzumesi, Anadolu insanını belgesel bir gerçekçilikle işler. Onun şiiri yalnızca biçimsel yenilikler açısından değil, toplumsal meseleleri cesurca dile getirmesi bakımından da çığır açıcıdır.\n\nOrhan Veli, Melih Cevdet Anday ve Oktay Rifat''ın öncülük ettiği Garip akımı, 1941''de kaleme alınan bir manifesto ile başlamıştır. Bu akım şiirden musikili ve süslü dili dışlayarak gündelik konuşma diline ve sıradan insanların yaşamına yönelmiştir. Sonraki dönemde İkinci Yeni hareketi ise anlam belirsizliğini ve bilinçdışını ön plana çıkarmıştır. Cemal Süreya ve Turgut Uyar bu dönemin öncü isimleridir.',
  ARRAY['şiir','edebiyat','Cumhuriyet','TYT'], 'published'),

  (gen_random_uuid(), 'Kimyasal Tepkimeler ve Denge', 'Kimya', 'TYT', 3, 295, 3,
E'Kimyasal tepkimeler, bir ya da birden fazla maddenin farklı özelliklere sahip yeni maddeler oluşturmak üzere dönüştüğü süreçlerdir. Tepkimeler ekzotermik (ısı açığa çıkaran) ya da endotermik (ısı soğuran) olabilir. Yanma, korozyon ve fotosentez doğada karşılaştığımız kimyasal tepkimelere örnektir.\n\nTepkime hızı birim zamanda tüketilen reaktant ya da oluşan ürün miktarıyla ifade edilir. Sıcaklık, konsantrasyon, yüzey alanı ve katalizörler tepkime hızını etkileyen başlıca faktörlerdir. Katalizörler, kendileri tükenmeksizin tepkime için gerekli olan aktivasyon enerjisini düşürerek hızı artıran maddelerdir.\n\nKimyasal denge, geri dönüşümlü bir tepkimede ileri ve geri tepkimelerin hızlarının eşitlendiği durumdur. Le Chatelier ilkesine göre bir denge sistemine dışarıdan baskı uygulandığında sistem bu baskıyı dengeleyecek yönde kayar. Örneğin konsantrasyon artırıldığında sistem ürün oluşumunu hızlandırır; sıcaklık değiştirildiğinde ise ısıl denge değişir. Bu ilkeler kimya sanayiinde ürün verimini optimize etmek için yaygın olarak kullanılır.',
  ARRAY['kimya','tepkime','denge','TYT'], 'published'),

  (gen_random_uuid(), 'Atom Modelleri ve Kuantum Teorisi', 'Kimya', 'TYT', 4, 320, 4,
E'Atomun yapısını anlamaya yönelik tarihsel süreç, her yeni gözlemle birlikte modellerin evrilmesini beraberinde getirmiştir. John Dalton''ın 19. yüzyılda önerdiği model atomu bölünemez katı bir küre olarak tasavvur etti. Thomson''ın elektron keşfinin ardından "üzümlü kek" modeli ortaya çıktı; buna göre negatif yüklü elektronlar pozitif yüklü bir madde içine gömülüydü.\n\nRutherford''ın altın levha deneyi (1911), atomun büyük bölümünün boş uzaydan ibaret olduğunu ve pozitif yükün çekirdek adı verilen küçük bir bölgede yoğunlaştığını ortaya koydu. Bohr ise buna elektronların belirli enerji düzeylerinde (yörüngelerde) döndüğünü ekledi ve hidrojen atomunun spektrumunu başarıyla açıkladı.\n\nModern kuantum mekaniği, elektronların kesin konumlarının belirsizlik ilkesi nedeniyle saptanamayacağını ortaya koymuştur. Bunun yerine elektronların uzayda belirli bölgelerde bulunma olasılığını gösteren orbital kavramı kullanılmaktadır. Schrödinger denkleminin çözümleri olan dalga fonksiyonları bu olasılık dağılımlarını matematiksel olarak ifade eder. Bu anlayış atom spektroskopisi, kimyasal bağlar ve maddenin genel özelliklerini açıklamada temel kaynak olmaktadır.',
  ARRAY['atom','kuantum','kimya','TYT'], 'published'),

  (gen_random_uuid(), 'Dalga Hareketi ve Ses Fiziği', 'Fizik', 'TYT', 3, 285, 3,
E'Dalgalar enerjiyi maddeden maddeye aktaran salınım hareketleridir. Mekanik dalgalar yayılmak için bir ortam gerektirirken elektromanyetik dalgalar (ışık, radyo vb.) boşlukta da yayılabilir. Ses dalgaları mekanik dalgalara örnektir; bu nedenle uzayın sessizliğinde ses işitilemez.\n\nSesin hızı ortama göre değişir. Havada yaklaşık 343 m/s olan ses hızı, sıvılarda ve katılarda çok daha yüksektir. Sıcaklık arttıkça hava molekülleri daha hızlı hareket edeceğinden sesin hızı da artar. Frekansı insan kulağının duyamayacağı kadar yüksek olan ultrasonik dalgalar tıbbi görüntülemede ve sonar teknolojisinde yaygın biçimde kullanılır.\n\nDoppler etkisi, ses veya ışık kaynağı ile gözlemci arasındaki görece hareketin frekansı değiştirdiği ilginç bir olgudur. Yaklaşan bir arabanın sireni daha tiz (yüksek frekans), uzaklaşan arabanın sireni ise daha pes (düşük frekans) duyulur. Astronomlar bu etkiyi galaksilerin uzaklaşma hızlarını ölçmekte ve evrenin genişlediğini doğrulamakta kullanmaktadırlar.',
  ARRAY['dalga','ses','fizik','TYT'], 'published'),

  (gen_random_uuid(), 'Tanzimat Edebiyatı ve Yenilik', 'Edebiyat', 'TYT', 3, 290, 3,
E'Tanzimat Dönemi (1839-1876), Osmanlı toplumunda Batı tarzı modernleşmenin edebiyata yansıdığı önemli bir dönemdir. Bu dönemde roman, hikâye, tiyatro ve gazete gibi Batılı türler Türk edebiyatıyla buluşmuş; toplumsal sorunlar sanatsal ifadenin merkezine yerleşmiştir.\n\nBirinci kuşak Tanzimat yazarları arasında Şinasi, Namık Kemal ve Ziya Paşa öne çıkar. Namık Kemal vatanseverlik, özgürlük ve vatan sevgisini eserlerinde işleyerek toplumsal bilinci uyandırmayı hedeflemiştir. "Vatan Yahut Silistre" adlı tiyatro eseri büyük yankı uyandırmıştır. Şinasi ise Türkçe gazete geleneğini kurmuş ve noktalama işaretlerini yaygınlaştırmıştır.\n\nİkinci kuşak yazarlarından Recaizade Mahmut Ekrem ve Abdülhak Hamit Tarhan ise daha bireysel ve estetik kaygıları ön plana çıkarmıştır. Samipaşazade Sezai ilk psikolojik romanlar yazmıştır. Bu dönemde "sanat toplum içindir" ile "sanat sanat içindir" tartışmaları edebiyat dünyasını derinden etkilemiş; ilerleyen yıllarda Servet-i Fünun akımına zemin hazırlamıştır.',
  ARRAY['tanzimat','edebiyat','tarih','TYT'], 'published'),

  (gen_random_uuid(), 'Enzimler ve Metabolizma', 'Biyoloji', 'TYT', 3, 300, 3,
E'Enzimler, canlı hücrelerde gerçekleşen kimyasal tepkimeleri hızlandıran biyolojik katalizörlerdir. Protein yapısındaki bu moleküller substrat adı verilen belirli moleküllere son derece seçici biçimde bağlanarak tepkime hızını milyonlarca kat artırabilirler. Bu seçicilik "anahtar-kilit" metaforuyla açıklanır: enzimin aktif bölgesi yalnızca belirli bir substrata uyum sağlar.\n\nMetabolizma, hücrede gerçekleşen tüm kimyasal tepkimelerin bütününü kapsar. Katabolik tepkimeler büyük molekülleri parçalayarak enerji açığa çıkarırken anabolik tepkimeler küçük moleküllerden büyük yapılar oluşturur. Glikoliz, sitrik asit döngüsü ve oksidatif fosforilasyon glikozdan ATP (hücresel enerji para birimi) üretiminin ardışık aşamalarıdır.\n\nEnzim aktivitesi sıcaklık, pH ve substrat konsantrasyonu gibi faktörlerden etkilenir. Her enzimin optimal çalıştığı bir sıcaklık ve pH aralığı bulunur. Aşırı sıcaklık enzimin üç boyutlu yapısını bozarak (denatürasyon) aktivitesini kaybettirir. Pek çok hastalık enzim eksikliği ya da işlevsizliğinden kaynaklanmaktadır; bu nedenle enzimler ilaç araştırmalarında önemli hedefler arasında yer almaktadır.',
  ARRAY['enzim','metabolizma','biyoloji','TYT'], 'published'),

  (gen_random_uuid(), 'Türk Edebiyatında Modernizm', 'Edebiyat', 'TYT', 3, 295, 3,
E'20. yüzyılın ortasında dünya edebiyatında yaşanan modernist akım Türk edebiyatında da derin izler bırakmıştır. Modernizm, bireysel deneyimi, bilinç akışını ve zaman anlayışındaki kırılmaları ön plana çıkarmıştır. Geleneksel anlatı yapısının yerini karmaşık iç sesler ve parçalı anlatılar almıştır.\n\nOğuz Atay ve Yusuf Atılgan Türk modernizminin önemli temsilcilerindendir. Atay''ın "Tutunamayanlar" romanı, modernist anlatı teknikleri ile Türk aydınının kimlik bunalımını birleştirdiği çığır açıcı bir eserdir. Atılgan''ın "Aylak Adam" adlı eseri ise varoluşçu izlekler taşıyan yabancılaşma temasını işler.\n\nModernist Türk edebiyatı, Batı edebiyatındaki akımları körü körüne taklit etmek yerine yerel gerçeklikle harmanlama yolunu seçmiştir. Kente göç, geleneksel değerlerin çözülmesi ve kimlik arayışı bu edebiyatın başlıca temaları olmuştur. Günümüzde ise postmodern eğilimler güçlenmiş; Orhan Pamuk ve Elif Şafak gibi yazarlar uluslararası edebiyat sahnesinde Türk sesini duyurmaktadır.',
  ARRAY['modernizm','edebiyat','roman','TYT'], 'published');

-- ══════════════════════════════════════════════════════════════
-- ALES METİNLERİ (10 adet) — Difficulty 3-5
-- ══════════════════════════════════════════════════════════════

INSERT INTO text_library (id, title, category, exam_type, difficulty, word_count, estimated_read_time, body, tags, status)
VALUES
  (gen_random_uuid(), 'Bilimsel Düşünme ve Araştırma Metodolojisi', 'Akademik', 'ALES', 4, 360, 4,
E'Bilimsel düşünme, sistematik gözleme, denetlenebilir hipotezlere ve tutarlı mantık zincirlerine dayanır. Bir fenomeni açıklamak için hipotez kurmak, ardından bu hipotezi yanlışlamaya çalışmak Karl Popper''ın yanlışlanabilirlik ölçütünün özüdür. Bilim, doğruluğu kanıtlanmış değil, henüz yanlışlanamamış önermeler bütünüdür.\n\nKolektifte araştırma metodolojisi nicel ve nitel olmak üzere iki temel paradigmayı kapsar. Nicel araştırmalar istatistiksel analiz ve ölçmeye dayanırken nitel araştırmalar katılımcı deneyimlerini yorumsamacı bir çerçevede inceler. Karma yöntem yaklaşımı ise her iki paradigmayı sentezleyerek daha kapsamlı bulgular elde etmeyi amaçlar.\n\nİç geçerlilik bir araştırmanın kendi içinde tutarlı olup olmadığını, dış geçerlilik ise sonuçların farklı bağlamlara genellenip genellenemeyeceğini sorgular. Örnekleme yöntemi, ölçüm güvenilirliği ve değişkenleri kontrol etme kapasitesi araştırmanın bilimsel değerini doğrudan belirler. Sistematik derleme ve meta-analiz ise birden fazla çalışmanın bulgularını sentezleyerek kanıt tabanını güçlendiren yöntemlerdir.',
  ARRAY['metodoloji','bilim','araştırma','ALES'], 'published'),

  (gen_random_uuid(), 'Dil Edinimi ve Evrimsel Kökenler', 'Dilbilim', 'ALES', 4, 345, 4,
E'Dil edinimi, çocukların karmaşık dilbilgisel yapıları neden explicit öğretim almaksızın hızla kavrayabildiklerini sorusunu inceleyen dilbilimin en çekici araştırma alanlarından biridir. Noam Chomsky''nin evrensel dilbilgisi hipotezi, insanların doğuştan bir dil edinim mekanizmasına sahip olduğunu öne sürer.\n\nKritik dönem hipotezine göre dil edinimi için biyolojik olarak belirlenmiş hassas bir pencere mevcuttur. Bu dönem ergenlik öncesinde kapanmakta ve sonrasında birinci dil edinimi giderek zorlaşmaktadır. Feral çocuklar üzerine yapılan çalışmalar bu hipotezi desteklemekle birlikte etik nedenlerle kontrollü deneyler yapılamamaktadır.\n\nEvrimsel dilbilim, insan dilinin nasıl ortaya çıktığını araştırır. Anatomik kanıtlar modern dil yeteneğinin yaklaşık 200.000 yıl önce Homo sapiens''te şekillendiğini düşündürmektedir. FOXP2 geni konuşma ve dil gelişiminde kritik rol oynamakta olup Neandertallerde de benzer bir versiyonunun bulunduğu saptanmıştır. Bu bulgular dilin kökenini salt biyolojik değil, kültürel-biyolojik ortak bir evrim süreci olarak ele almamızı gerektirmektedir.',
  ARRAY['dilbilim','dil','evrim','ALES'], 'published'),

  (gen_random_uuid(), 'Yapay Zeka ve Etik Sorunlar', 'Teknoloji', 'ALES', 4, 350, 4,
E'Yapay zeka sistemleri giderek artan yetenekleriyle insan karar alma süreçlerinin yerini almakta ya da bu süreçlere ortak olmaktadır. Bu dönüşüm beraberinde önemli etik soruları gündeme getirmektedir. Bir özerk sistem zarar verdiğinde sorumluluk kime aittir: yazılımcıya mı, kullanıcıya mı, yoksa üretici şirkete mi?\n\nAlgoritmik önyargı, yapay zeka sistemlerinin eğitim verilerindeki sosyal eşitsizlikleri yeniden üretmesi ya da pekiştirmesi anlamına gelir. Suç tahmin sistemleri, kredi notlandırma algoritmaları ve işe alım araçları üzerinde yapılan çalışmalar bu sistemlerin belirli demografik gruplar aleyhine orantısız biçimde çalışabildiğini göstermektedir. Önyargısız eğitim verisi oluşturmak ise kendi başına zorlu bir etik ve teknik sorundur.\n\nAçıklanabilirlik yapay zekanın en çok tartışılan konularından biridir. Derin öğrenme modelleri "kara kutu" niteliği taşıdığından kararlarını neden verdiklerini insanın anlayabileceği biçimde açıklamak güçtür. Tıbbi tanı, cezai adalet gibi yüksek riskli alanlarda açıklanabilirlik bir ön koşul olmalı mıdır? Yapay zeka yönetişimi konusunda uluslararası standartlar oluşturma çalışmaları sürmektedir.',
  ARRAY['yapay zeka','etik','teknoloji','ALES'], 'published'),

  (gen_random_uuid(), 'Ekonomik Büyüme Teorileri', 'Ekonomi', 'ALES', 4, 335, 4,
E'Ekonomik büyüme neden bazı ülkelerde sürekli ve hızlı iken diğerlerinde yavaş ya da tersine döner? Bu temel soru iktisatçıları onlarca yıldır meşgul etmektedir. Klasik büyüme modelleri sermeye ve emeği birincil üretim faktörleri olarak ele alırken Solow modeli teknolojik ilerlemenin uzun dönem büyümedeki belirleyici rolünü vurgulamıştır.\n\nİçsel büyüme teorileri, teknolojik değişimi modelin dışında değil içinde açıklama girişimidir. Paul Romer''ın öncülük ettiği bu yaklaşım, insan sermayesine ve Ar-Ge''ye yapılan yatırımların artan getiri sağladığını öne sürer. Bu bağlamda eğitim ve kurumsal kalite uzun vadeli büyümenin kritik belirleyicileri hâline gelir.\n\nKurumsal iktisat anlayışı ise mülkiyet hakları, hukuk devleti ve güvenilir piyasa kurallarının varlığının büyüme için salt fiziksel sermayeden daha belirleyici olduğunu savunur. Tarihin en hızlı kalkınma deneyimlerini yaşayan Güney Kore ve Tayvan vakaları kurumsal reformlarla ihracata dayalı sanayileşmenin bütünleşik bir strateji olarak hayata geçirildiğini göstermektedir.',
  ARRAY['ekonomi','büyüme','kalkınma','ALES'], 'published'),

  (gen_random_uuid(), 'Sosyolojide Kimlik ve Kültür', 'Sosyoloji', 'ALES', 4, 325, 4,
E'Sosyolojik açıdan kimlik, bireyin toplumsal roller, grup üyelikleri ve kültürel pratikler aracılığıyla inşa ettiği öznel ve toplumsal bir yapıdır. Kimlik ne doğuştan sabit bir öz ne de salt toplumsal koşullanmanın ürünüdür; her ikisi arasındaki dinamik gerilimde sürekli biçimlenmektedir.\n\nKültür, bir toplumun değerlerini, normlarını, sembollerini ve pratiklerini kuşaktan kuşağa aktaran yaşayan bir miras olarak tanımlanabilir. Küreselleşme süreci yerel kültürleri hem zenginleştiren hem de homojenleştiren çeşitli baskılar üretmektedir. Kültürel melezlik, farklı kültürlerin buluşmasından ortaya çıkan yeni ifade biçimlerini tanımlar.\n\nSosyal kimlik teorisi (Tajfel ve Turner) bireylerin mensubu oldukları gruptan olumlu bir öz-kavram türetmeye güdülendiğini öne sürer. Bu süreç iç grup kayırmacılığı ve dış gruba karşı önyargı eğilimlerini pekiştirebilir. Interseksiyonellik (Kimberlé Crenshaw) ise kimliğin ırk, sınıf, toplumsal cinsiyet gibi bileşenlerinin birbirinden bağımsız değil, kesişen ve birbirini güçlendiren eksenlerde anlaşılması gerektiğini vurgular.',
  ARRAY['kimlik','kültür','sosyoloji','ALES'], 'published'),

  (gen_random_uuid(), 'Felsefede Bilgi Kuramı (Epistemoloji)', 'Felsefe', 'ALES', 5, 355, 4,
E'Epistemoloji, bilginin doğası, kaynağı, kapsamı ve güvenilirliğini sorgulayan felsefe dalıdır. "Neyi bilebiliriz?" ve "Bir inancın bilgi sayılabilmesi için ne gereklidir?" soruları bu alanın merkezinde yer alır. Geleneksel tanıma göre bilgi "doğrulanmış doğru inanç" olarak tanımlanmıştır; ancak Edmund Gettier''ın 1963''te öne sürdüğü karşı örnekler bu tanımı köklü biçimde sarsmıştır.\n\nRasyonalizm, saf aklın duyu deneyiminden bağımsız olarak güvenilir bilgi üretebileceğini savunur. Descartes''ın "Cogito ergo sum" (Düşünüyorum, öyleyse varım) özdeyişi bu yaklaşımın simgesidir. Empirizm ise tüm bilginin nihayetinde duyusal deneyimden kaynaklandığını öne sürer; Locke, Berkeley ve Hume bu geleneğin baş temsilcileridir. Kant ise "Saf Aklın Eleştirisi" adlı yapıtında her iki geleneği sentezleyerek a priori bilginin zihindeki kategoriler ve formlara dayandığını göstermiştir.\n\nÇağdaş epistemoloji sosyal boyutu giderek daha fazla önemsemektedir. Feminist epistemoloji bilginin nesnel değil, perspektife bağlı olduğunu ve egemen bakış açısının kimin deneyiminin "evrensel" sayılacağını belirlediğini öne sürer. Sanal epistomik topluluklarda bilginin nasıl üretildiği ve dolaşıma girdiği ise dijital çağın yeni araştırma gündemleri arasına girmiştir.',
  ARRAY['epistemoloji','felsefe','bilgi','ALES'], 'published'),

  (gen_random_uuid(), 'Psikolojide Bilişsel Süreçler', 'Psikoloji', 'ALES', 4, 340, 4,
E'Bilişsel psikoloji, insanın bilgiyi nasıl algıladığını, işlediğini, depoladığını ve kullandığını inceler. 1950''lerde davranışçılığa yönelik tepki olarak doğan bu yaklaşım, zihin süreçlerini bilgisayar metaforu çerçevesinde kavramsallaştırmıştır.\n\nDikkat, duyusal uyaranlar arasından belirli olanları seçip işleyen zihinsel kaynakların dağılımıdır. Filtre teorileri (Broadbent, Treisman) farklı aşamalarda gerçekleşen bu filtreleme süreçlerini açıklamaktadır. Çalışma belleği ise anlık bilgiyi geçici olarak tutan ve işleme tabi kılan kapasitesi sınırlı bir sistemdir; Baddeley''ın modelinde merkezi yönetici, sesli döngü ve uzamsal-görsel taslak gibi alt bileşenler tanımlanmıştır.\n\nBilişsel yanlılıklar, insanın bilgiyi işleme ve karar verme süreçlerinde sergilediği sistematik hata örüntüleridir. Daniel Kahneman''ın Sistem 1 (hızlı, otomatik, sezgisel) ve Sistem 2 (yavaş, çabalı, analitik) ayrımı bu yanlılıkların çoğunu açıklamaktadır. Doğrulama yanlılığı, çapalama etkisi ve mevcutluk sezgisi en yaygın bilişsel yanlılıklar arasında sayılmaktadır.',
  ARRAY['psikoloji','biliş','karar','ALES'], 'published'),

  (gen_random_uuid(), 'Küresel İklim Değişikliği', 'Çevre Bilimleri', 'ALES', 3, 325, 4,
E'Yirminci yüzyılın ortasından bu yana fosil yakıt yakılması, ormansızlaşma ve sanayi emisyonları atmosferdeki sera gazı konsantrasyonlarını dramatik biçimde artırmıştır. Karbondioksit seviyesi sanayi öncesi 280 ppm değerinden 420 ppm''i aşan güncel değerine yükselmiştir. Bu değişim sera etkisini güçlendirerek küresel ortalama sıcaklıkta 1,1 °C''lik bir artışa neden olmuştur.\n\nİklim değişikliğinin somut etkileri polar bölgelerde özellikle belirgindir: Arktik deniz buzu rekor düşük seviyelere gerilemiş, buzul erimesi deniz seviyesinin yükselmesini hızlandırmaktadır. Aşırı hava olaylarının sıklığı ve şiddeti artmakta; seller, kuraklıklar ve tropik fırtınalar giderek daha yıkıcı boyutlar kazanmaktadır.\n\nParis Anlaşması (2015) küresel ısınmayı 2 °C ile sınırlandırma ve tercihen 1,5 °C''de tutma hedefini ortaya koymuştur. Yenilenebilir enerjiye geçiş, enerji verimliliği, sürdürülebilir tarım ve karbon tutma teknolojileri bu hedefe ulaşmak için kritik araçlar olarak öne çıkmaktadır. Bununla birlikte mevcut politika taahhütleri bu hedeflerden hâlâ uzak kalmaktadır.',
  ARRAY['iklim','çevre','sürdürülebilirlik','ALES'], 'published'),

  (gen_random_uuid(), 'Nörobilim ve Bilinç', 'Nörobilim', 'ALES', 5, 350, 4,
E'Bilinç, nörobilimin en çetin sorularından birini oluşturmaktadır: Beynin nöral aktivitesi öznel deneyimi —sıcaklık hissi, renklerin algılanması ya da acı— nasıl üretmektedir? Filozoflar ve bilim insanları bu "zor problem"i açıklamak için yüzyıllardır mücadele etmektedir.\n\nGlobal alan teorisi (Dehaene ve Changeux) bilincin geniş kortikal ağlar arasındaki bilgi yayılımıyla ortaya çıktığını öne sürer. Entegre bilgi teorisi (Tononi) ise bilinci, bir sistemin entegre bilgi üretme kapasitesinin (phi değeri) bir işlevi olarak matematiksel biçimde tanımlamaya çalışır. Her iki yaklaşım da bilinçli ve bilinçsiz zihinsel süreçler arasındaki sınırı nöral ölçütlerle çizmeye çalışmaktadır.\n\nUyku, anestezi ve vejetatif durum çalışmaları bilinç mekanizmalarını tersine mühendislik yöntemiyle anlamlandırmada değerli veriler sunmaktadır. Nöroimgeleme teknolojilerindeki (fMRI, EEG) gelişmeler kilitlenme sendromlu hastalar gibi davranışsal yanıt veremeyen bireylerde bilincin varlığını saptamamızı sağlamıştır. Yapay zeka sistemlerinin bilinç sahibi olup olamayacağı ise tartışmalar açısından çok daha derin felsefi katmanlar içermektedir.',
  ARRAY['nörobilim','bilinç','beyin','ALES'], 'published'),

  (gen_random_uuid(), 'İstatistiksel Analizde Temel Kavramlar', 'İstatistik', 'ALES', 4, 330, 4,
E'İstatistik, verilerin toplanması, düzenlenmesi, analizi ve yorumlanmasıyla ilgilenen bilim dalıdır. Betimleyici istatistik verileri özetlemeye yarayan ölçütleri (ortalama, ortanca, standart sapma gibi) kapsamaktadır. Çıkarımsal istatistik ise örneklem verilerinden ana kitleye ilişkin çıkarımlar yapmayı ve olasılık çerçevesinde hipotezleri sınamayı amaçlar.\n\nNormal dağılım (Gauss eğrisi) istatistiğin temel kavramlarından birini oluşturmaktadır. Pek çok doğal ve sosyal olgu normal dağılıma yakın bir yapı sergilediğinden bu dağılım özel bir öneme sahiptir. Z-skoru, bir değerin ortalamanın kaç standart sapma uzaklığında olduğunu verir ve dağılımlar arası karşılaştırmalara olanak tanır.\n\nHipotez testlerinde Type I hatası (gerçekte doğru olan sıfır hipotezini reddetmek) ve Type II hatası (gerçekte yanlış olan sıfır hipotezini kabul etmek) arasında bir denge kurulmak zorundadır. P değeri, verilen verinin sıfır hipotezi doğruyken gözlemlenmesi olasılığını ifade eder; 0,05 eşiği bilimsel çevrelerde yaygın kabul görmekle birlikte eleştirilmektedir. Büyük veri çağında istatistiksel anlamda anlamlı olanı pratik açıdan önemli olandan ayırt etmek giderek daha kritik bir beceri hâline gelmektedir.',
  ARRAY['istatistik','analiz','veri','ALES'], 'published');

-- ══════════════════════════════════════════════════════════════
-- KPSS METİNLERİ (10 adet) — Difficulty 2-4
-- ══════════════════════════════════════════════════════════════

INSERT INTO text_library (id, title, category, exam_type, difficulty, word_count, estimated_read_time, body, tags, status)
VALUES
  (gen_random_uuid(), 'Atatürk''ün Eğitim Reformları', 'Türk İnkılabı', 'KPSS', 2, 285, 3,
E'Mustafa Kemal Atatürk''ün önderliğinde gerçekleştirilen eğitim reformları, yeni kurulan Türkiye Cumhuriyeti''nin temellerini şekillendirmiştir. 1924''te Tevhid-i Tedrisat (Öğretim Birleştirme) Kanunu''nun çıkarılmasıyla tüm okullar Millî Eğitim Bakanlığı çatısı altında toplandı ve medreseler kapatıldı.\n\n1928''deki harf devrimi belki de en köklü kültürel dönüşümü simgelemektedir. Arap alfabesinin yerini Latin kökenli Türk alfabesi aldı. Ardından başlatılan millet mektepleri kampanyasıyla kısa sürede milyonlarca vatandaşa yeni alfabeyle okuma yazma öğretildi. Bu kampanyanın lideri Atatürk''ün bizzat köy köy dolaşarak ders vermesi tarihsel bir simge hâline gelmiştir.\n\n1933''te gerçekleştirilen üniversite reformuyla İstanbul Darülfünunu modernleştirilerek İstanbul Üniversitesi kuruldu. Nazizm''den kaçan Avrupalı akademisyenler Türkiye''ye davet edilerek yeni kurulan üniversitelere bilimsel katkı sağlamak üzere göreve çağrıldı. Köy Enstitüleri ise 1940''larda hayata geçirilen özgün bir eğitim modeliyle kırsal kesimde yetişmiş öğrencileri öğretmen ve kalkınma ajanı olarak yetiştirmeyi hedefledi.',
  ARRAY['Atatürk','eğitim','reform','KPSS'], 'published'),

  (gen_random_uuid(), 'Türkiye''nin Anayasal Düzeni', 'Hukuk', 'KPSS', 3, 300, 3,
E'Türkiye''nin yürürlükteki Anayasası 1982 yılında kabul edilmiş, o tarihten bu yana pek çok önemli değişikliğe uğramıştır. Temel hak ve özgürlükleri güvence altına alan, devletin temel yapısını ve kuvvetler ayrılığı ilkesini belirleyen bu belge modern hukuk devletinin temelini oluşturmaktadır.\n\nAnayasanın değiştirilemez maddeleri cumhuriyetin niteliklerini tanımlamaktadır: Türkiye, demokratik, laik ve sosyal bir hukuk devletidir. Yasama yetkisi Türkiye Büyük Millet Meclisi''ne ait olup tek meclisli bir yapı benimsenmiştir. 2017 anayasa değişiklikleriyle cumhurbaşkanlığı hükûmet sistemine geçilmiş ve yürütme yetkisi cumhurbaşkanlığında toplanmıştır.\n\nAnayasa Mahkemesi, yasaların anayasaya uygunluğunu denetlemekle görevlidir. Bireysel başvuru hakkı 2010''dan bu yana vatandaşlara, temel haklarının ihlal edildiğini düşündüklerinde doğrudan Anayasa Mahkemesi''ne gitme imkânı tanımaktadır. Türkiye, Avrupa İnsan Hakları Mahkemesi''nin yargı yetkisini de tanımış olup bu mahkemenin kararları iç hukuku etkilemektedir.',
  ARRAY['anayasa','hukuk','Türkiye','KPSS'], 'published'),

  (gen_random_uuid(), 'Millî Mücadele Dönemi ve Kurtuluş Savaşı', 'Tarih', 'KPSS', 2, 310, 3,
E'Birinci Dünya Savaşı''nın ardından imzalanan Mondros Mütarekesi (30 Ekim 1918) Osmanlı Devleti''ni İtilaf güçlerinin işgaline açık bıraktı. İzmir''in 15 Mayıs 1919''da Yunan kuvvetlerince işgal edilmesi ise Türk halkında derin bir direniş bilinci uyandırdı.\n\nMustafa Kemal Atatürk, 19 Mayıs 1919''da Samsun''a çıkışıyla Millî Mücadele''yi fiilen başlattı. Erzurum ve Sivas kongrelerinde alınan kararlar millî irade ve tam bağımsızlık ilkelerini temel direnek olarak belirledi. 23 Nisan 1920''de Ankara''da TBMM''nin açılmasıyla yeni Türk devletinin temelleri atılmış oldu.\n\nBatı Cephesi''nde yaşanan İnönü muharebeleri kritik zaferler kazandırdı. 26 Ağustos 1922''de başlayan Büyük Taarruz Yunan kuvvetlerini Anadolu''dan sürdü ve 9 Eylül''de İzmir''in kurtuluşuyla noktalandı. Lozan Antlaşması (24 Temmuz 1923) bu savaşı diplomatik açıdan resmileştirerek Türkiye Cumhuriyeti''nin sınırlarını uluslararası alanda tanıttı. 29 Ekim 1923''te ise cumhuriyet ilan edildi.',
  ARRAY['kurtuluş savaşı','tarih','Atatürk','KPSS'], 'published'),

  (gen_random_uuid(), 'Osmanlı Millet Sistemi', 'Tarih', 'KPSS', 3, 290, 3,
E'Osmanlı millet sistemi, imparatorluk bünyesindeki farklı etnik ve dinî toplulukların kendi iç işlerini yönetmelerine olanak tanıyan özgün bir idari düzenlemedir. Bu sistem altında Müslümanlar, Ortodoks Hristiyanlar, Ermeni Hristiyanlar ve Yahudiler ayrı topluluklar (milletler) biçiminde örgütlendi.\n\nHer millet kendi dini liderliği aracılığıyla kişisel statü hukuku, eğitim ve sosyal hizmetler alanlarında öz yönetim hakkına sahipti. Ermeni patrikhanesi, Rum Ortodoks ekümenik patrikhanesi ve Yahudi hahambaşılığı bu özerk yapıların kurumsal ifadeleriydi. Padişah ise çeşitli toplulukların haklarını güvence altına alan en yüksek otorite konumundaydı.\n\nMillet sistemi uzun süre belirli düzeyde bir toplumlar arası huzurun sürdürülmesini sağladı. Ancak 19. yüzyılda Batılı milliyetçilik akımlarının yayılması ve ekonomik çıkarlar bu dengeyi sarstı. Ayrılıkçı hareketlerin güçlenmesiyle birlikte imparatorluk çok cepheli toplumsal gerilimlerle yüzleşmek zorunda kaldı. Millet sisteminin mirası bugün de Balkanlar ve Orta Doğu''daki azınlık hakları tartışmalarında yankısını bulmaktadır.',
  ARRAY['osmanlı','millet sistemi','tarih','KPSS'], 'published'),

  (gen_random_uuid(), 'Türkiye''nin Ekonomik Kalkınma Süreci', 'Ekonomi', 'KPSS', 3, 300, 3,
E'Cumhuriyet''in ilk yıllarında Türkiye sanayisi son derece sınırlı bir düzeydeydi. Devletçilik ilkesi doğrultusunda kurulan devlet iktisadi teşekkülleri (KİT''ler) temel sanayi kollarını ve altyapı yatırımlarını kamu eliyle gerçekleştirdi. Sümerbank tekstil, Etibank madencilik ve KBI''ler demir-çelik üretiminde öncü kuruluşlar oldu.\n\n1980''lerde gerçekleştirilen ekonomik liberalizasyon programı kamu müdahalesini azaltarak dışa açık bir piyasa ekonomisine geçiş sürecini başlattı. İhracata yönelik büyüme modeli, Türkiye''nin 1990''lı yıllar boyunca ortalama yüzde beş civarında büyümesine katkıda bulundu. Aynı dönemde yüksek enflasyon, kamu açıkları ve döviz krizleri ekonomik istikrarın önündeki ciddi engeller olarak öne çıktı.\n\n2001 krizi ardından hayata geçirilen güçlü ekonomi programı bankacılık sektörünü köklü biçimde yeniden yapılandırdı ve enflasyonu tek haneli rakamların altına indirdi. 2000''li yıllarda yabancı yatırım girişleri hız kazanırken sanayi çıktısı ve ihracatta belirgin artışlar yaşandı. Orta-yüksek gelir grubuna giren Türkiye, gelişmiş ülkelerle gelir açığını kapatma konusunda ilerleme kaydetmekle birlikte verimliliği artırma ve ihracat ürün çeşitliliğini genişletme alanlarında önemli yapısal sorunlarla boğuşmaya devam etmektedir.',
  ARRAY['ekonomi','kalkınma','Türkiye','KPSS'], 'published'),

  (gen_random_uuid(), 'Türkiye''de Demokratikleşme Süreci', 'Siyasi Tarih', 'KPSS', 3, 285, 3,
E'Türkiye''de çok partili siyasi hayat 1946''da fiilen başlamış ve 1950 seçimlerinin ardından iktidarda el değişiminin yaşanmasıyla pekişmiştir. Adnan Menderes liderliğindeki Demokrat Parti''nin iktidara gelişi Türk demokrasisinin köklü bir dönüşümünü simgelemiştir.\n\nTürkiye''nin demokratikleşme süreci kesintisiz bir çizgi izlememiş; 1960, 1971 ve 1980''de askeri müdahalelerle sekteye uğramıştır. Her müdahalenin ardından sivil yönetime dönüş sağlanmış, ancak siyasi kültür ve kurumsal yapı üzerindeki kalıcı izler derin biçimde hissedilmiştir. 1982 Anayasası askeri yönetim döneminde hazırlanmış ve temel hakları kısıtlayan düzenlemeler içermiştir.\n\nAvrupa Birliği üyelik sürecinde yürütülen reformlar yargı bağımsızlığı, azınlık hakları ve sivil denetim alanlarında önemli değişiklikler getirmiştir. 2000''li yılların başında demokratikleşme adına atılan bu adımlar insan hakları örgütlerince olumlu karşılanmıştır. Bununla birlikte basın özgürlüğü, yargı bağımsızlığı ve muhalefete yönelik kısıtlamalar gibi konularda endişeler varlığını sürdürmektedir.',
  ARRAY['demokrasi','siyaset','tarih','KPSS'], 'published'),

  (gen_random_uuid(), 'Türkiye''nin Dış Politikası', 'Dış Politika', 'KPSS', 3, 280, 3,
E'Türkiye''nin dış politikası, jeopolitik konumunun şekillendirdiği özgün bir denklem içinde Batı ittifakları, bölgesel güçler ve yükselen küresel aktörler arasında hassas bir denge kurma çabasını yansıtmaktadır. NATO''nun kurucusu ve uzun süreli üyesi olan Türkiye, Batı savunma mimarisinin kilit bir unsurunu oluşturmaktadır.\n\nTürkiye-AB ilişkileri 1999''da adaylık statüsünün tanınmasıyla yeni bir boyut kazanmış; ancak sonraki dönemde müzakereler askıya alınmış ve ilişkiler gerilemiştir. Öte yandan Türkiye bölgesel liderlik rolüne soyunarak Kafkasya, Orta Doğu ve Balkanlar''da etkin bir politika izlemektedir. "Sıfır sorun" olarak kavramsallaştırılan komşularla ilişkileri normalleştirme politikası başlangıçta umut verici sonuçlar doğurmuş; ancak Arap Baharı sonrası gelişmeler bu politikanın sınırlarını açığa çıkarmıştır.\n\nRusya ile ilişkiler özellikle enerji bağımlılığı (TürkAkım boru hattı), savunma alımları (S-400) ve Suriye politikasındaki farklılıklar nedeniyle karmaşık bir yapı sergilemektedir. Türkiye''nin çok boyutlu dış politikası zaman zaman müttefikleriyle gerilimlere yol açmakta, bununla birlikte Ankara''nın bölgesel arabuluculuk kapasitesini de pekiştirmektedir.',
  ARRAY['dış politika','Türkiye','jeopolitik','KPSS'], 'published'),

  (gen_random_uuid(), 'Anadolu''nun Coğrafi Özellikleri', 'Coğrafya', 'KPSS', 2, 270, 3,
E'Anadolu Yarımadası üç tarafı denizlerle çevrili bir coğrafi bütündür: batıda Ege Denizi, kuzeyde Karadeniz ve güneyde Akdeniz. Bu yarımada yaklaşık 755.000 km² yüzölçümüyle dağlık ve plato niteliği ağır basan bir coğrafyaya sahiptir.\n\nAnadolu''nun iç bölgelerini Orta Anadolu Platosu kaplar; ortalama yüksekliği 1.000-1.200 metre arasında değişen bu platoda karasal iklim egemendir. Kuzey ve güney kıyıları boyunca uzanan dağ sıraları —Karadeniz Dağları ile Toroslar— iç bölgelere iklimsel etkilerin nüfuzunu önler ve kıyılar ile iç kesimler arasında belirgin bir iklim kuşaklanması yaratır.\n\nAnadolu''nun su kaynakları tarih boyunca stratejik önem taşımıştır. Fırat, Dicle, Kızılırmak ve Yeşilırmak başlıca akarsular arasındadır. Güneydoğu Anadolu Projesi (GAP), Fırat ve Dicle üzerinde inşa edilen barajlar ve sulama sistemleriyle bölgenin ekonomik potansiyelini harekete geçirmeyi amaçlayan kapsamlı bir kalkınma programıdır.',
  ARRAY['coğrafya','Anadolu','Türkiye','KPSS'], 'published'),

  (gen_random_uuid(), 'İnsan Hakları ve Türkiye', 'Hukuk', 'KPSS', 3, 280, 3,
E'İnsan hakları, salt ülkeden ülkeye değişen yasal düzenlemelere değil; bireyin yalnızca insan olması nedeniyle sahip olduğu evrensel haklara dayanır. 1948 BM İnsan Hakları Evrensel Beyannamesi bu anlayışın kurucu belgesidir ve onu imzalayan devletler temel standartları korumayı taahhüt etmiştir.\n\nTürkiye, Avrupa İnsan Hakları Sözleşmesi''ni onaylamış ve Avrupa İnsan Hakları Mahkemesi''nin yargı yetkisini kabul etmiştir. Bu mekanizma bireylerin hak ihlali iddiasıyla devleti uluslararası bir mahkeme önüne çıkarabilmesine olanak tanır. Türkiye''nin Strasbourg''dan aldığı mahkûmiyet kararları çoğunlukla ifade özgürlüğü, gözaltı süreleri ve adil yargılanma hakkı ile ilgili olmuştur.\n\n1982 Anayasası''nda 2001 ve sonraki yıllarda yapılan değişiklikler temel hak ve özgürlüklerin kapsamını genişletmeyi amaçlamıştır. İşkence yasağı mutlak hâle getirilmiş, tutukluluk süreleri kısaltılmış ve bazı hakların kullanımındaki kısıtlamalar yumuşatılmıştır. Sivil toplum kuruluşları ve basın özgürlüğü alanında kaydedilen gelişmeler ile süregelen sorunlar gündemin odağında kalmaya devam etmektedir.',
  ARRAY['insan hakları','hukuk','Türkiye','KPSS'], 'published'),

  (gen_random_uuid(), 'İkinci Dünya Savaşı ve Türkiye', 'Tarih', 'KPSS', 3, 285, 3,
E'Türkiye İkinci Dünya Savaşı''na fiilen katılmamış; ancak ülke bu süre zarfında ağır diplomatik baskılarla karşı karşıya kalmıştır. Alman kuvvetlerinin 1941''de Balkanlar''ı işgal etmesi Türkiye''nin yakın çevresini doğrudan tehdit altına almıştır.\n\nTürkiye''nin tarafsızlığını koruma stratejisi hem Mihver hem de İtilaf devletleriyle hassas ikili ilişkilerin dengelenmesini gerektirmiştir. Ülke Almanya ile 1941''de bir saldırmazlık paktı imzalamış; öte yandan İngiltere ve ABD ile ekonomik ve diplomatik bağlarını koparmamıştır. Almanya''ya krom ihracatının sürdürülmesi önemli bir tartışma konusu olmuş ve zamanla kısıtlamalar getirilmiştir.\n\nTürkiye''nin savaşın son aşamasında Almanya''ya savaş ilan etmesi (Şubat 1945) Birleşmiş Milletler''in kurucu üyeleri arasında yer almak için stratejik bir zorunluluktu. Savaşın Türkiye üzerindeki ekonomik etkileri ağır olmuştur: Varlık Vergisi (1942) azınlık tüccarları orantısız biçimde etkileyerek toplumsal gerginliklere yol açmıştır. Savaş sonrasında Türkiye NATO üyeliğine doğru yönelerek siyasi duruşunu Batı Bloğu yanında net biçimde belirlemiştir.',
  ARRAY['tarih','ikinci dünya savaşı','Türkiye','KPSS'], 'published');

-- ══════════════════════════════════════════════════════════════
-- GENERAL METİNLERİ (10 adet) — Difficulty 1-3
-- ══════════════════════════════════════════════════════════════

INSERT INTO text_library (id, title, category, exam_type, difficulty, word_count, estimated_read_time, body, tags, status)
VALUES
  (gen_random_uuid(), 'Uzay Keşfinin Geleceği', 'Teknoloji', 'General', 2, 300, 3,
E'İnsanlığın uzayı keşfetme itkisi Sputnik''in fırlatılmasından (1957) bu yana hız kazanarak sürmektedir. Bugün artık devlet ajanslarının yanı sıra SpaceX, Blue Origin ve diğer özel şirketler uzay yarışına ortak olmuş ve maliyetleri dramatik biçimde düşürerek erişimi demokratikleştirmektedir.\n\nAy''a geri dönüş planları gündemin üst sıralarına yerleşmiştir. NASA''nın Artemis programı 2020''li yıllarda insanlı Ay görevlerini hedeflemekte olup bu sefer amacın kalıcı bir üs kurmak olduğu vurgulanmaktadır. Mars ise uzun vadeli hedefler arasında birinci sıraya oturmuştur; astronot sağlığı üzerindeki uzun süreli uzay yolculuğu etkileri bu misyonun önündeki en büyük engeldir.\n\nUzay araştırmacıları uydular, teleskoplar ve uzay istasyonları aracılığıyla Güneş Sistemi''ni ve ötesini haritalandırmaya devam etmektedir. James Webb Uzay Teleskobu daha önce hiç bu kadar ayrıntıyla görüntülenemeyen erken evren galaksilerini ve öte gezegen atmosferlerini gözler önüne sermektedir. Uzay keşfi yalnızca bilimsel bilgiyi genişletmemekte; aynı zamanda Dünya''da günlük hayatı köklü biçimde dönüştüren sayısız teknolojik yan ürün üretmektedir.',
  ARRAY['uzay','teknoloji','bilim','General'], 'published'),

  (gen_random_uuid(), 'Meditasyonun Beyne Etkisi', 'Sağlık', 'General', 2, 285, 3,
E'Meditasyon binlerce yıllık geçmişe sahip bir zihinsel pratik olmasına karşın bilimsel araştırmacılar bu alana yalnızca son otuz yılda ilgi duymaya başlamıştır. Dikkat ve öz-farkındalığı geliştirmeye odaklanan bu pratiğin beyin üzerindeki etkileri artık nöroimgeleme teknolojileriyle ölçülebilmektedir.\n\nDüzenli meditasyon pratiğinin amigdalayı (korku ve kaygı işleyen beyin bölgesi) küçülttüğünü, öte yandan prefrontal korteks hacmini artırdığını gösteren çalışmalar dikkat çekmektedir. Bu bölge karar alma ve duygusal düzenlemeyle ilişkilidir. Farkındalık meditasyonu stresin biyolojik göstergesi olan kortizol düzeylerini düşürmekte ve bağışıklık sistemini olumlu yönde etkilemektedir.\n\nFarkındalığa dayalı bilişsel terapi (MBCT) tekrarlayan depresyon vakalarında etkili bir tedavi yöntemi olarak kabul görmüş ve klinik kılavuzlara girmiştir. Bununla birlikte meditasyonun tüm etkileri henüz netlik kazanmamış olup plasebo kontrolünü sağlamak metodolojik açıdan güçtür. Öte yandan araştırma bulguları yalnızca birkaç haftalık düzenli pratiğin bile ölçülebilir faydalar yarattığına işaret etmektedir.',
  ARRAY['meditasyon','sağlık','beyin','General'], 'published'),

  (gen_random_uuid(), 'Türk Mutfağının Zengin Tarihi', 'Kültür', 'General', 1, 265, 2,
E'Türk mutfağı, Orta Asya''nın göçebe geleneklerini Anadolu''nun bereketli tarım kültürü ve Osmanlı saray mutfağının inceliğiyle harmanlamıştır. Coğrafi ve kültürel bu çeşitlilik, bölgeden bölgeye köklü biçimde değişen lezzet ve malzeme zenginliğini doğurmuştur.\n\nEkmek Türk mutfağının merkezinde yer alır: köy ekmekleri, lavaş, pide ve simit Türk sofralarının vazgeçilmez unsurlarıdır. Kebap kültürü yüzyıllarca yayılan coğrafyaların birikimini taşır; Adana''nın acılı kıyma kebabından Bursa''nın efsanevi İskender''ine uzanan bu geniş yelpaze Türk mutfağının çeşitliliğini yansıtır. Balık Ege ve Karadeniz kıyılarında sofraların baş tacı olurken İç Anadolu''da et ve buğday ağırlıklı yemekler ön plana çıkar.\n\nTatlılar da o denli çeşitlidir. Baklava, künefe, kazandibi ve aşure farklı teknikleri ve tatları yansıtır. Türk kahvesi ve çayın kültürel önemi yalnızca bir içecek boyutunu çok aşmakta; toplumsal ilişkilerin, sohbetin ve misafirperverliğin simgeleri olarak anlam kazanmaktadır. Türk mutfağı 2010''da UNESCO tarafından Somut Olmayan Kültürel Miras listesine alınan Türk kahvesi kültürüyle uluslararası alanda tanınırlık kazanmaya devam etmektedir.',
  ARRAY['yemek','kültür','tarih','General'], 'published'),

  (gen_random_uuid(), 'Dijital Çağda Mahremiyet', 'Teknoloji', 'General', 2, 290, 3,
E'İnternetin günlük hayatımıza girmesiyle birlikte kişisel verilerin toplanması, depolanması ve analiz edilmesi olağanüstü boyutlara ulaşmıştır. Her arama sorgusu, alışveriş tercihi ve sosyal medya etkileşimi şirketler ve hükümetler tarafından derlenen dijital bir iz bırakmaktadır.\n\nVeri gizliliği endişeleri yalnızca kişisel bilgilerin ifşa edilmesiyle sınırlı kalmamaktadır. Kişisel verilere dayalı profilleme, reklam hedeflemesi ve siyasi mesaj kişiselleştirmesinin bireyin özerkliğini nasıl etkilediği sorusu tartışmaların odağına taşınmıştır. Cambridge Analytica skandalı ve benzeri vakalar büyük veri manipülasyonunun toplumsal sonuçlarını gözler önüne sermiştir.\n\nAvrupa Birliği''nin Genel Veri Koruma Yönetmeliği (GDPR), bireylere kişisel verileri üzerinde daha güçlü haklar tanıyan kapsamlı bir düzenleyici çerçeve sunmaktadır. Erişim hakkı, silinme hakkı ve veri taşınabilirliği bu haklar arasında sayılabilir. Türkiye de 6698 sayılı Kişisel Verilerin Korunması Kanunu ile bu alanda benzer güvenceler getirmiştir.',
  ARRAY['mahremiyet','teknoloji','veri','General'], 'published'),

  (gen_random_uuid(), 'Yapay Zeka Günlük Hayatı Nasıl Değiştiriyor?', 'Teknoloji', 'General', 2, 300, 3,
E'Yapay zeka artık bilim kurgu filmlerinin değil, gündelik hayatın ayrılmaz bir parçasıdır. Akıllı telefon asistanlarından müzik öneri algoritmalarına, e-posta spam filtrelerinden yüz tanıma sistemlerine kadar YZ pek çok uygulama tarafından sessizce çalıştırılmaktadır.\n\nSağlık alanında YZ, radyoloji görüntülerini tarayarak doktorların gözden kaçırabileceği ince patolojileri tespit edebilmektedir. İlaç keşfini hızlandırmak ve kişiselleştirilmiş tedavi protokolleri geliştirmek için büyük veri setlerini analiz etmektedir. Eğitimde ise uyarlanabilir öğrenme platformları her öğrencinin hızına ve anlayış seviyesine göre içerik ve geri bildirim kişiselleştirmektedir.\n\nÖte yandan YZ tabanlı otomasyon işgücü piyasasını yeniden biçimlendirmektedir. Rutin ve yinelemeli görevler hızla otomasyona geçerken yaratıcılık, eleştirel düşünme ve duygusal zeka içeren meslekler daha dirençli bir görünüm sergilemektedir. Gelecek işgücünün YZ ile iş birliği yapma becerisini edinmesi öncelikli bir eğitim hedefi hâline gelmektedir.',
  ARRAY['yapay zeka','teknoloji','gelecek','General'], 'published'),

  (gen_random_uuid(), 'Okyanusların Gizemli Derinlikleri', 'Doğa', 'General', 2, 280, 3,
E'Dünya''nın yüzeyinin yüzde yetmişinden fazlasını kaplayan okyanuslar, gezegenimizin en az keşfedilmiş bölgelerini barındırmaktadır. Okyanus tabanının yüzde sekseninden fazlası hâlâ haritalandırılmamış durumdadır; bu oran Ay''ın yüzeyindeki haritalandırılmamış alandan bile yüksektir.\n\nDerin okyanus ekosistemleri, ışık ve sıcaklığın aşırı yetersizliğine karşın olağanüstü biyoçeşitlilik barındırmaktadır. Hidrotermik bacalar (siyah ışıltılar) güneş enerjisi yerine kimyasal enerjiyi (kemotrofik) kullanan canlıların yaşadığı benzersiz habitatlardır. Bu ekosistemlerin keşfi yaşamın oksijenin ve fotosentezin bulunmadığı ortamlarda da var olabileceğini kanıtlaması açısından tarihsel bir öneme sahiptir.\n\nOkyanuslar küresel iklim sisteminin düzenlenmesinde kritik bir rol oynamaktadır. Büyük miktarlarda karbondioksit emen ve ısıyı depolayan okyanuslar, atmosferdeki iklim etkilerini uzun süre boyunca dengeleme işlevi görmüştür. Okyanus asitliğindeki artış, ısınma ve kirlilik ise bu ekosistemlerin sağlığını ciddi biçimde tehdit etmektedir.',
  ARRAY['okyanus','doğa','bilim','General'], 'published'),

  (gen_random_uuid(), 'Müziğin Psikolojik Etkileri', 'Kültür', 'General', 2, 275, 3,
E'Müzik, insan beynini diğer hiçbir sanat türünden farklı biçimlerde etkileyen güçlü bir olgudur. Müzik dinlemek; ödül, duygu, hafıza ve hareketle ilişkili birden fazla beyin bölgesini eş zamanlı olarak aktive etmektedir. Bir şarkının dinleyende goosebumps (tüyler ürpermesi) yaratması, beynin dopamin salgılaması ve zevk merkezlerinin ateşlenmesiyle ilişkilidir.\n\nMüziğin terapi aracı olarak kullanımı onlarca yıldır araştırılmaktadır. Müzik terapi ağrıyı azaltmakta, kaygıyı yatıştırmakta ve Alzheimer hastalarında uzun süreli anıların yüzeye çıkmasına yardımcı olmaktadır. Bu son olgu son derece dikkat çekicidir: Hastalık nedeniyle pek çok anısını yitirmiş bireyler gençliklerinde sevdikleri şarkıları çoğu kez kolaylıkla hatırlayabilmektedir.\n\nMüziğin öğrenmeye etkisi de kapsamlı biçimde çalışılmıştır. "Mozart Etkisi" hipotezi aşırı genelleştirilmiş olmakla birlikte müzik eğitiminin çocuklarda dil becerilerini, matematiksel düşünceyi ve yürütücü işlevleri geliştirdiğine dair güçlü kanıtlar mevcuttur. Ritim ve melodi hafıza ile dili desteklemekte; bu yüzden bazı eğitimciler içerikleri ezber yoluyla öğretmeyi tercih etmektedir.',
  ARRAY['müzik','psikoloji','sağlık','General'], 'published'),

  (gen_random_uuid(), 'Yeşil Enerji ve Sürdürülebilir Gelecek', 'Çevre', 'General', 2, 290, 3,
E'Fosil yakıtlara olan küresel bağımlılığı azaltmak hem çevre hem de ekonomik açıdan zorunlu bir hedef hâline gelmiştir. Güneş ve rüzgar enerjisi teknolojileri son on yılda dramatik maliyet düşüşleri yaşayarak birçok bölgede kömür ve gaz santrallerine kıyasla daha ekonomik seçenekler hâline gelmiştir.\n\nGüneş paneli verimliliği yıllar içinde sürekli iyileşmiş, üretim maliyeti ise çarpıcı biçimde gerilemiştir. Açık deniz rüzgar çiftlikleri, karadan çok daha güçlü ve sürekli rüzgar kaynaklarına erişim sağlayarak enerji üretimini önemli ölçüde artırmaktadır. Hidrojen ekonomisi, yenilenebilir enerjinin depolanabileceği ve taşıtlar ile sanayi için yakıt olarak kullanılabileceği temiz bir gelecek vaat etmektedir.\n\nYenilenebilir enerjiye geçişin önündeki temel engeller üretilen enerjinin depolanması ve ızgara entegrasyonu sorunlarıdır. Batarya depolama teknolojilerindeki gelişmeler bu soruna çözüm yolları sunmakta; "akıllı enerji ızgaraları" hem arz hem talebi daha verimli dengelemeye olanak tanımaktadır. Türkiye yenilenebilir enerji kapasitesini artırmakta ve bu alanda hem güneş hem de rüzgar enerjisi kurulu gücünde kayda değer ilerleme kaydetmektedir.',
  ARRAY['enerji','çevre','sürdürülebilirlik','General'], 'published'),

  (gen_random_uuid(), 'Kuantum Fiziğinin Sırları', 'Bilim', 'General', 3, 295, 3,
E'Kuantum mekaniği, atom altı parçacıkların davranışını inceleyen ve klasik fiziğin sezgilerimizi alt üst eden çıkarımlarıyla şimdiye kadar formüle edilmiş en başarılı bilimsel teorilerden biridir. Dalga-parçacık ikiliği, bir elektronun hem dalga hem de parçacık özellikleri sergilediğini ortaya koyar; hangi özelliğin gözlemleneceğini ölçüm koşulları belirler.\n\nHeisenberg''in belirsizlik ilkesi bir parçacığın konumunun ve momentumunun aynı anda sonsuz hassasiyetle ölçülemeyeceğini söyler. Bu durum ölçüm cihazlarının yetersizliğinden değil, doğanın temel özelliğinden kaynaklanmaktadır. Kuantum dolanıklığı ise iki parçacığın aralarındaki mesafeden bağımsız olarak eş zamanlı şekilde birbirini etkileyebildiği gizemli bir olgudur; Einstein bu durumu "uzaktan ürkütücü etki" olarak nitelendirmiştir.\n\nKuantum bilgisayarlar klasik bilgisayarların üstesinden gelemeyeceği hesaplamaları gerçekleştirme potansiyeli taşımaktadır. Süperpozisyon ilkesini kullanan kuantum bitleri (qubit) aynı anda hem 0 hem de 1 değerini temsil edebildiğinden paralel işlem kapasitesi üstel biçimde artmaktadır. Bu teknoloji şifreleme, ilaç keşfi ve yapay zeka alanlarını kökten dönüştürebilecek potansiyel barındırmaktadır.',
  ARRAY['kuantum','fizik','bilim','General'], 'published'),

  (gen_random_uuid(), 'Dilin Evrimi ve Geleceği', 'Dilbilim', 'General', 3, 285, 3,
E'Dil, insanı diğer türlerden ayıran en temel özelliklerden biridir. Bugün dünyada konuşulan 7.000 civarındaki dilden yüzlercesi gelecek yüzyılda yok olma riskiyle karşı karşıyadır. Küreselleşme ve dijital iletişim egemen dillerin yayılımını hızlandırırken küçük toplulukların dillerini yaşatması giderek zorlaşmaktadır.\n\nDillerin tarihi seyri, karmaşık göç ve kültürel etkileşim süreçlerini yansıtır. Hintavrupa dil ailesi pek çok Avrupalı ve Asya dilini kapsamakta; binlerce yıl önce yaşamış ortak ata dili Proto-Hintavrupa, karşılaştırmalı dilbilim yöntemiyle yeniden kurgulanabilmektedir. Türk dilleri ise Orta Asya''dan Anadolu''ya uzanan geniş bir coğrafyaya yayılmış kendine özgü bir dil ailesi oluşturmaktadır.\n\nDijital çağ dilin kendisini de dönüştürmektedir. Emoji''ler, kısaltmalar ve internet jargonu yazı dilinde yeni ifade araçları yaratmaktadır. Yapay zeka çeviri araçları dil engellerini aşmayı kolaylaştırsa da kültürel nüansları ve bağlam odaklı anlamı tam olarak aktarmak hâlâ güçtür. Dil kayıplarının belgelenmesi ve miras dillerinin dijital araçlarla canlandırılması dilbilimcilerin ve toplulukların ortak gündemine girmiş bir sorumluluktur.',
  ARRAY['dil','dilbilim','kültür','General'], 'published');

END $$;
