-- ================================================================
-- 031_library_questions.sql
-- 52 metin × 3 soru = 156 comprehension sorusu
-- Her metin: main_idea + detail + inference
-- ================================================================

DO $$
DECLARE tid uuid;
BEGIN
IF (SELECT COUNT(*) FROM text_questions) > 10 THEN RETURN; END IF;

-- ══════════════════════════════════════════════════════════════
-- LGS
-- ══════════════════════════════════════════════════════════════

SELECT id INTO tid FROM text_library WHERE title='Hücrenin Yapısı ve Organelleri';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metnin ana konusu nedir?','["Yalnızca hücre zarının yapısı","Hücrenin temel bileşenleri ve organellerin işlevleri","DNA molekülünün çift sarmal yapısı","Fotosentez sırasında açığa çıkan enerji"]',1,'Metin hücreyi tüm bileşenleriyle ele almakta; zar, sitoplazma, çekirdek ve organel işlevlerini açıklamaktadır.',2,1),
(tid,'detail','Hücrenin hangi organeli "enerji santrali" olarak tanımlanmaktadır?','["Ribozom","Kloroplast","Mitokondri","Çekirdek"]',2,'Metinde mitokondri, besinlerden enerji elde ederek ATP ürettiği için enerji santrali olarak adlandırılmaktadır.',2,2),
(tid,'inference','Prokaryot hücrelerle ilgili ne çıkarılabilir?','["Büyük ve karmaşık yapılıdır","Kloroplast içerirler","Çekirdek zarı bulunmaz","Yalnızca hayvan hücrelerinde görülür"]',2,'Metin "çekirdek kontrol merkezidir" ifadesiyle zarla çevrili çekirdek vurgularken prokaryotlarda bu yapının olmadığı çıkarılabilir.',3,3);

SELECT id INTO tid FROM text_library WHERE title='Türkiye''nin Coğrafi Bölgeleri';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Metin esas olarak neyi açıklamaktadır?','["Türkiye''nin komşu ülkelerini","Yedi coğrafi bölgenin iklim ve ekonomik özelliklerini","Türkiye''nin nüfus dağılımını","Anadolu''nun jeolojik oluşumunu"]',1,'Metin yedi coğrafi bölgeyi iklim, bitki örtüsü ve ekonomik etkinlikler açısından karşılaştırmalı biçimde ele almaktadır.',2,1),
(tid,'detail','Akdeniz Bölgesi''nin öne çıkan ekonomik özelliği nedir?','["Ağır sanayi tesisleri","Turizm ve tarım","Kömür madenciliği","Hayvancılık"]',1,'Metinde Akdeniz Bölgesi turizm ve subtropikal tarım ürünleriyle öne çıkan bir bölge olarak tanımlanmaktadır.',2,2),
(tid,'inference','Karadeniz Bölgesi''nin çay yetiştiriciliğinde öncü olması hakkında ne söylenebilir?','["Karadeniz en kalabalık bölgedir","Bol yağış ve ılıman iklim uygun koşullar sağlar","Kömür madenciliği çay arazilerini beslemiştir","Diğer bölgeler çay üretimine elverişli değildir"]',1,'Yüksek yağış ve ılıman iklimin Karadeniz Bölgesi''ni çay tarımına olanak tanıdığı metinden anlaşılmaktadır.',2,3);

SELECT id INTO tid FROM text_library WHERE title='Işığın Kırılması ve Optik Olaylar';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Metnin odaklandığı temel fizik olgusu nedir?','["Sesin havada yayılması","Işığın ortam değiştirirken kırılması ve bunun sonuçları","Elektromanyetik dalgaların frekansı","Renklerin dalga boyları"]',1,'Metin ışığın ortam sınırında hızını ve yönünü değiştirmesini (kırılma) ve bu olgunun prizma, mercek ve gökkuşağındaki uygulamalarını açıklamaktadır.',3,1),
(tid,'detail','Gökkuşağı hangi optik olaylar zinciriyle oluşur?','["Yalnızca yansıma","Kırılma, iç yansıma ve tekrar kırılma","Yalnızca kırılma","Difraksyon ve girişim"]',1,'Metinde gökkuşağının yağmur damlalarında kırılma, iç yansıma ve ikinci kırılma sonucunda oluştuğu belirtilmektedir.',3,2),
(tid,'inference','Işığın suya girince yavaşlaması, snell yasasına göre ne anlama gelir?','["Işık tamamen geri yansır","Işık kırılarak yön değiştirir","Renk tayf değişmez","Frekans azalır"]',1,'Snell yasası kırılma açısının ortamların kırılma indisine bağlı olduğunu gösterir; hız azalınca ışın normal''e yaklaşarak kırılır.',3,3);

SELECT id INTO tid FROM text_library WHERE title='Osmanlı''nın Yükseliş Dönemi';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Metin Osmanlı Devleti''nin hangi dönemini ele almaktadır?','["Kuruluş ve Yükseliş Dönemi''ni","Duraklama ve Gerileme Dönemi''ni","Tanzimat Reformları''nı","Osmanlı''nın son yüzyılını"]',0,'Metin kuruluştan Kanuni dönemine kadar uzanan yükseliş sürecini incelemektedir.',2,1),
(tid,'detail','Fatih Sultan Mehmet''in 1453''te İstanbul''u fethetmesinin tarihsel önemi nedir?','["Osmanlı''yı çöküşe götürmüştür","Ortaçağ''ı kapatıp Yeniçağ''ı açmıştır","Hilafeti Osmanlı''ya kazandırmıştır","Tımar sistemini başlatmıştır"]',1,'Metinde İstanbul''un fethinin Ortaçağ''ı sona erdirip Yeniçağ''ı başlatan dönüm noktası olduğu vurgulanmaktadır.',2,2),
(tid,'inference','Millet sistemi hangi amaca hizmet etmiştir?','["Yalnızca Müslüman toplulukları korumak","Farklı etnik ve dinî toplulukların bir arada yaşamasını sağlamak","Yeniçeri ordusunu güçlendirmek","Vergi toplamayı kolaylaştırmak"]',1,'Metinde millet sisteminin çeşitli toplulukların Osmanlı çatısı altında bir arada yaşamasına olanak tanıdığı belirtilmektedir.',2,3);

SELECT id INTO tid FROM text_library WHERE title='Türkçede Sözcük Türleri';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metin hangi dilbilgisi konusunu açıklamaktadır?','["Türkçe cümle yapısı","Sözcüklerin anlamsal ve işlevsel sınıflandırması","Türkçenin ses uyumları","Yazım kuralları"]',1,'Metin Türkçedeki sözcük türlerini (isim, sıfat, fiil vb.) anlamsal ve işlevsel açıdan sınıflandırarak açıklamaktadır.',1,1),
(tid,'detail','Hangi sözcük türü eylemi, oluşu veya durumu ifade eder?','["İsim","Zarf","Fiil","Bağlaç"]',2,'Metinde fiillerin eylem, oluş ve durumu ifade eden sözcükler olduğu açıklanmaktadır.',1,2),
(tid,'inference','Sıfat sözcükleri cümlede neden önemlidir?','["Cümleye bağımsız anlam kazandırır","İsimleri niteleyerek anlamı zenginleştirir","Fiil çekimi sağlar","Sözcükler arasında bağ kurar"]',1,'Sıfatlar isimleri niteleyen ya da belirten sözcükler olduğundan cümledeki anlam zenginliğine doğrudan katkı sağlar.',2,3);

SELECT id INTO tid FROM text_library WHERE title='Besinlerin Sindirimi ve Emilimi';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metnin temel konusu nedir?','["Kan dolaşımı","Sindirim sisteminde besinlerin parçalanması ve emilmesi","Solunum organlarının yapısı","Boşaltım sistemi"]',1,'Metin besinlerin sindirim sisteminde mekanik ve kimyasal olarak parçalanmasını ve ince bağırsakta emilimini açıklamaktadır.',2,1),
(tid,'detail','Emilimin en yoğun gerçekleştiği organ hangisidir?','["Mide","Ağız","İnce bağırsak","Karaciğer"]',2,'Metinde villusların yüzey alanını artırarak besin emilimini en çok ince bağırsakta sağladığı belirtilmektedir.',2,2),
(tid,'inference','Enzimlerin sindirim için neden gerekli olduğu anlaşılmaktadır?','["Besinlere renk katarlar","Büyük molekülleri emilir hâle dönüştürürler","Vücudu mikroplardan korurlar","Midedeki asidi nötrleştirirler"]',1,'Enzimler büyük besin moleküllerini (nişasta, protein, yağ) küçük ve emilir formlara (glikoz, amino asit, yağ asidi) parçaladıkları için sindirim için zorunludur.',2,3);

SELECT id INTO tid FROM text_library WHERE title='Elektrik ve Manyetizma';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Metnin ele aldığı iki temel fizik olgusu nedir?','["Ses ve ısı","Elektrik ve manyetizma ile aralarındaki ilişki","Işık ve optik","Mekanik ve enerji"]',1,'Metin elektrik yük hareketini, akımı ve manyetik alanları inceleyerek bu iki fenomen arasındaki ilişkiyi açıklamaktadır.',3,1),
(tid,'detail','Transformatörler hangi prensibe dayanır?','["Ohm Yasası","Elektromanyetik endüksiyon","Kirchhoff akım yasası","Coulomb kuvveti"]',1,'Metinde transformatörlerin değişen manyetik alanın endüksiyon yoluyla gerilim dönüştürdüğünü açıklamaktadır.',3,2),
(tid,'inference','Mıknatısın çevresindeki manyetik alan hakkında ne çıkarılabilir?','["Sadece mıknatısın içinde etkilidir","Uzaklaştıkça zayıflayan bir kuvvet alanı oluşturur","Sadece demir cinsinden maddeleri etkiler","Elektrik akımıyla hiçbir ilgisi yoktur"]',1,'Manyetik alan çizgileri mıknatıstan uzaklaştıkça seyrekleşir, yani alan kuvveti mesafeyle azalır; bu metin genelinden çıkarılabilir.',3,3);

SELECT id INTO tid FROM text_library WHERE title='Ekosistem ve Biyoçeşitlilik';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metin esas olarak neyi açıklamaktadır?','["İnsan vücudunun organlarını","Ekosistemlerin yapısını ve canlı çeşitliliğinin önemini","Bitkilerin fotosentez sürecini","Atmosferin katmanlarını"]',1,'Metin biyotik-abiyotik bileşenleri, besin zincirlerini ve biyoçeşitliliğin ekosistem sağlığı için önemini ele almaktadır.',2,1),
(tid,'detail','Biyoçeşitlilik kaybı ekosistemleri nasıl etkiler?','["Üretkenliği artırır","Yalnızca büyük memelileri etkiler","Direnci azaltarak sistemi kırılganlaştırır","İklim değişikliğini durdurur"]',2,'Metinde biyoçeşitliliğin ekosistemi dengelemek ve strese karşı dirençli kılmak için kritik olduğu vurgulanmakta; kayıpların kırılganlığa yol açtığı belirtilmektedir.',2,2),
(tid,'inference','Besin zincirindeki bir halkanın yok olması nasıl bir sonuç doğurabilir?','["Yalnızca o türü etkiler","Zincirin tüm halkalarını ve dengeyi bozabilir","Biyoçeşitliği artırır","Abiyotik faktörler devreye girerek dengeyi korur"]',1,'Bir halkanın ortadan kalkması, hem yukarı hem aşağı beslenen organizmaları etkileyerek tüm dengeyi bozabilir.',3,3);

SELECT id INTO tid FROM text_library WHERE title='Anadolu Medeniyetleri';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Metin hangi konuyu ele almaktadır?','["Yalnızca Hitit devletini","Anadolu''da kurulan uygarlıkların tarihsel seyrini","Türk göçlerinin Anadolu''ya etkisini","Osmanlı öncesi Bizans dönemini"]',1,'Metin Çatalhöyük''ten başlayarak Hitit, Frig, Lidya, Pers ve Roma gibi Anadolu''yu yurt edinen uygarlıkları tarihsel sırayla ele almaktadır.',2,1),
(tid,'detail','Anadolu''nun en eski yerleşim merkezlerinden biri olarak kabul edilen yer hangisidir?','["Efes","Çatalhöyük","Troia","Sard"]',1,'Metinde Çatalhöyük''ün MÖ 7500''e uzanan ve en eski kent toplulukları arasında sayılan bir yerleşim yeri olduğu belirtilmektedir.',2,2),
(tid,'inference','Anadolu''nun farklı medeniyetleri barındırması hakkında ne söylenebilir?','["Coğrafi yalnızlık uygarlıkları korumuştur","Stratejik konumu ticaret ve kültür alışverişini kolaylaştırmıştır","Yalnızca askeri güç başarıyı sağlamıştır","Uygarlıklar birbirinden bağımsız gelişmiştir"]',1,'Anadolu''nun Asya ile Avrupa arasındaki köprü konumu ticaret yollarını ve kültürel aktarımı kolaylaştırarak çok sayıda uygarlığa ev sahipliği yapmasını sağlamıştır.',2,3);

SELECT id INTO tid FROM text_library WHERE title='Demokrasi ve Temel Haklar';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metnin odak noktası nedir?','["Cumhuriyet ile demokrasinin farkı","Demokrasinin ilkeleri ve temel insan haklarıyla ilişkisi","Seçim sistemlerinin karşılaştırması","Anayasal monarşi modelleri"]',1,'Metin demokrasinin hukukun üstünlüğü, bireysel özgürlükler ve hesap verebilirlik ilkelerini ele alarak temel haklarla bağlantısını kurmaktadır.',2,1),
(tid,'detail','Hukukun üstünlüğü ilkesi ne anlama gelir?','["Yalnızca hâkimlerin kurallara uyması","Hem yöneticilerin hem de yönetilenlerin yasalara eşit biçimde bağlı olması","Yasama organının denetlenmemesi","Güçlü liderlik ile adaletin sağlanması"]',1,'Metinde hukukun üstünlüğü yöneticiler dahil tüm kesimlerin yasalara tabi olduğu sistemi ifade etmektedir.',2,2),
(tid,'inference','Demokratik ülkelerde bağımsız yargı neden gereklidir?','["Yalnızca suçları cezalandırmak için","Yürütme organının denetlenmesini ve temel hakların güvence altına alınmasını sağlamak için","Yasama organını temsil etmek için","Ekonomik büyümeyi hızlandırmak için"]',1,'Bağımsız yargı, yürütme erkinin aşırıya kaçmasını önleyen ve demokratik dengeyi koruyan temel bir unsurdur.',3,3);

-- ══════════════════════════════════════════════════════════════
-- TYT
-- ══════════════════════════════════════════════════════════════

SELECT id INTO tid FROM text_library WHERE title='Evrenin Yapısı ve Kozmoloji';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metnin temel konusu nedir?','["Güneş Sistemi''nin oluşumu","Evrenin kökeni, yapısı ve büyük patlama teorisi","Kara deliklerin iç yapısı","Galaksilerin sınıflandırılması"]',1,'Metin evrenin ~13.8 milyar yıl önceki büyük patlama ile başladığını, yapısını ve kozmolojik gelişimini ele almaktadır.',3,1),
(tid,'detail','Büyük Patlama teorisine göre evren nasıl başlamıştır?','["Önceki bir evrenden dönüşümle","Aşırı yoğun ve sıcak tek bir noktadan genişlemeyle","Büyük bir patlama değil yavaş bir oluşumla","Birden fazla evrenin birleşmesiyle"]',1,'Metinde evrenin yaklaşık 13.8 milyar yıl önce aşırı yoğun ve sıcak bir noktadan büyük patlama ile başladığı vurgulanmaktadır.',3,2),
(tid,'inference','Karanlık madde ile ilgili ne çıkarılabilir?','["Teleskoplarla doğrudan görülebilir","Varlığı dolaylı gözlemlerle anlaşılmaktadır","Evrenin yalnızca küçük bir bölümünü oluşturur","Büyük patlama ile ortaya çıkmıştır"]',1,'Karanlık madde ışık yaymadığından doğrudan gözlemlenemez; varlığı yalnızca yer çekimi etkileri üzerinden çıkarılabilmektedir.',4,3);

SELECT id INTO tid FROM text_library WHERE title='DNA''nın Keşfi ve Genetik Devrim';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metin hangi bilimsel keşif ve gelişmeleri ele almaktadır?','["Hücre bölünmesi","DNA''nın yapısının keşfedilmesi ve genetiğin bilime katkıları","Evrim teorisinin tarihi","Protein sentez mekanizması"]',1,'Metin Watson ve Crick''in çift sarmal modelinden günümüz genetik teknolojisine uzanan süreci anlatmaktadır.',3,1),
(tid,'detail','Watson ve Crick''in DNA keşfindeki en önemli katkısı nedir?','["DNA''nın adenin içerdiğini bulmak","Çift sarmal modeli ortaya koymak","Gen terapisini geliştirmek","Genomu haritalandırmak"]',1,'Metinde Watson ve Crick''in 1953''te yayımladıkları çift sarmal modelin modern genetiğin temeli olduğu belirtilmektedir.',3,2),
(tid,'inference','İnsan Genomu Projesi''nin önemi ne olabilir?','["Yalnızca tarihsel kayıt amacı taşır","Hastalıkların genetik temelini anlayarak tedaviyi dönüştürür","Yalnızca adli tıpla ilgilidir","Evrimsel araştırmalara katkısı yoktur"]',1,'Tüm insan genomunun haritalanması, kalıtsal hastalıkların teşhis ve tedavisinde devrim niteliğinde bir temel oluşturmuştur.',4,3);

SELECT id INTO tid FROM text_library WHERE title='Termodinamiğin Yasaları';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Metin hangi fizik dalını açıklamaktadır?','["Kuantum mekaniği","Isı, iş ve enerji dönüşümünü inceleyen termodinamik","Akışkanlar mekaniği","Nükleer fizik"]',1,'Metin termodinamiğin dört yasasını ve enerji dönüşümü ile entropi kavramlarını ele almaktadır.',4,1),
(tid,'detail','İkinci Termodinamik Yasası''nın entropi hakkındaki ifadesi nedir?','["Entropi sabit kalır","Kapalı sistemlerde entropi zamanla azalır","Kapalı sistemlerde entropi eğilimsel olarak artar","Entropi yalnızca sıvılarda geçerlidir"]',2,'Metinde İkinci Yasa''nın kapalı sistemlerde entropinin (düzensizliğin) zamanla artma eğiliminde olduğunu ortaya koyduğu belirtilmektedir.',4,2),
(tid,'inference','Sonsuz hareket makinesi neden yapılamaz?','["Sürtünme koşullar altında azaltılabilir","Birinci Yasa enerji korunumunu, İkinci Yasa enerji dönüşümündeki kayıpları zorunlu kılar","Madde enerjiyle aynı şeydir","Kuantum etkileri makro ölçekte geçerli değildir"]',1,'Enerji dönüşümleri her zaman kayıp (entropi artışı) içerdiğinden ve enerji yoktan var edilemeyeceğinden sonsuz enerji çıkaran makine fizik yasalarına aykırıdır.',4,3);

SELECT id INTO tid FROM text_library WHERE title='Organik Kimya Temelleri';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metinde hangi kimya dalı tanıtılmaktadır?','["İnorganik kimya","Karbon bileşiklerini inceleyen organik kimya","Nükleer kimya","Analitik kimya"]',1,'Metin organik kimyayı karbon bileşikleri, fonksiyonel gruplar ve organik reaksiyonlar temelinde açıklamaktadır.',4,1),
(tid,'detail','Organik kimyada fonksiyonel grupların rolü nedir?','["Bileşiğin fiziksel boyutunu belirler","Molekülün kimyasal davranışını ve reaktivitesini belirler","Yalnızca bileşiğin rengini etkiler","Erime noktasını düşürür"]',1,'Metinde fonksiyonel grupların organik moleküllerin kimyasal özelliklerini ve reaksiyonlarını belirleyen yapısal birimler olduğu açıklanmaktadır.',4,2),
(tid,'inference','Karbon atomunun çok sayıda bileşik oluşturabilmesi neye bağlıdır?','["Tek bir bağ yapabilmesine","Dört değerliği sayesinde zincirleme ve halka yapılar kurabilmesine","En ağır element olmasına","Radyoaktif özellik taşımasına"]',1,'Karbonun dört değerliği sayesinde hem karbon hem de diğer atomlarla çeşitli bağlar kurarak organik kimyanın temelini oluşturan büyük çeşitlilik sağlanmaktadır.',4,3);

SELECT id INTO tid FROM text_library WHERE title='Sinir Sistemi ve Nöronlar';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metnin konusu nedir?','["Dolaşım sistemi","Sinir sisteminin yapısı ve nöronların iletişim mekanizması","Hormonal sistem","Bağışıklık sistemi"]',1,'Metin MSS/PSS ayrımı, nöron anatomisi ve elektrokimyasal sinyal iletimini ele almaktadır.',3,1),
(tid,'detail','Miyelin kılıfı nöronlarda ne işlev görür?','["Nörona enerji sağlar","Elektriksel iletimi hızlandırır","Nörona besin taşır","Sinapslarda nörotransmitter salgılar"]',1,'Metinde miyelin kılıfının iletimi hızlandıran yalıtkan tabaka olduğu ve bazı hastalıklarda bu kılıfın hasar gördüğünde iletim bozukluğu yaşandığı açıklanmaktadır.',3,2),
(tid,'inference','Sinaptik iletim hakkında ne çıkarılabilir?','["Nöronlar doğrudan birbirine bağlıdır","Kimyasal haberci maddeler sinyali boşlukta taşır","Elektrik akımı sinaptik aralığı geçer","İletim yalnızca tek yönlüdür"]',1,'Sinaptik boşlukta nörotransmitterlerin bir nörondan diğerine sinyal taşıdığı metinden anlaşılmaktadır.',3,3);

SELECT id INTO tid FROM text_library WHERE title='Cumhuriyet Dönemi Türk Şiiri';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Metin hangi edebi dönemi ele almaktadır?','["Divan şiiri","Cumhuriyet''in ilanı sonrası gelişen modern Türk şiiri","Tanzimat dönemi şiiri","Halk şiiri geleneği"]',1,'Metin Cumhuriyet döneminde şiirin hem biçimsel hem de tematikal açıdan nasıl değiştiğini ele almaktadır.',3,1),
(tid,'detail','Garip Hareketi şiire hangi yeniliği getirmiştir?','["Aruz veznini yeniden canlandırmıştır","Sıradan insanı ve gündelik yaşamı şiirin merkezine taşımıştır","Divan estetiğini sürdürmüştür","Epik şiiri ön plana çıkarmıştır"]',1,'Metinde Orhan Veli ve arkadaşlarının kurduğu Garip Hareketi''nin sıradan insanı ve günlük konuşma dilini şiire taşıdığı belirtilmektedir.',3,2),
(tid,'inference','Cumhuriyet dönemi şiirinin çeşitliği neyi yansıtmaktadır?','["Tek bir ideolojik çizgiye bağlılığı","Farklı estetik arayışlar ve toplumsal meselelerin çoğulluğunu","Yalnızca siyasi kaygıları","Geleneksel Osmanlı estetiğine dönüşü"]',1,'Toplumcu gerçekçilik, İkinci Yeni ve Garip gibi birbirinden ayrışan akımların aynı dönemde var olması şiirde çoğulcu ve dinamik bir tabloya işaret etmektedir.',3,3);

SELECT id INTO tid FROM text_library WHERE title='Kimyasal Tepkimeler ve Denge';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metinde temel olarak ne açıklanmaktadır?','["Maddenin hâl değişimleri","Kimyasal tepkimelerin türleri ve denge kavramı","Periyodik tablo","Asit-baz nötralizasyonu"]',1,'Metin kimyasal dönüşümlerin türlerini, Le Chatelier ilkesini ve dinamik dengeyi ele almaktadır.',3,1),
(tid,'detail','Le Chatelier ilkesine göre denge sistemi dışsal bir etkiye nasıl yanıt verir?','["Tepkime durur","Sistem etkiyi azaltacak yönde kaymalar gerçekleştirir","Ürün ve reaktif konsantrasyonları değişmez","Sistem tamamen bozulur"]',1,'Metinde Le Chatelier ilkesinin dengeye uygulanan baskıyı azaltmak için sistemin tepki vereceğini öngördüğü açıklanmaktadır.',3,2),
(tid,'inference','Tepkime hızını artırmak için katalizörler neden kullanılır?','["Ürün miktarını artırırlar","Aktivasyon enerjisini düşürerek tepkimeyi hızlandırırlar","Denge sabitini artırırlar","Reaktifleri doğrudan ürüne dönüştürürler"]',1,'Katalizörler aktivasyon enerjisi eşiğini düşürerek daha fazla molekülün tepkimelere girmesini sağlar; bu nedenle hız artar.',3,3);

SELECT id INTO tid FROM text_library WHERE title='Atom Modelleri ve Kuantum Teorisi';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Metin hangi tarihsel gelişim sürecini incelemektedir?','["Kimyasal bağlanma teorisi","Atom modellerinin Dalton''dan kuantum mekaniğine evrimi","Nükleer füzyon","Elektromanyetik spektrum"]',1,'Metin atom modellerinin Dalton''un bilardo topu anlayışından Bohr ve ardından kuantum mekaniğine uzanan evrimi anlatmaktadır.',4,1),
(tid,'detail','Bohr modelinin Rutherford modeline göre temel farkı nedir?','["Çekirdeğin varlığını keşfetmiştir","Elektronların belirli enerji düzeylerinde (yörüngelerde) hareket ettiğini öne sürmüştür","Atomun bölünmez olduğunu ileri sürmüştür","Kuantum belirsizliğini açıklamıştır"]',1,'Metinde Bohr''un elektronların belirli enerji seviyelerinde bulunduğunu ve bu seviyelere ait enerji değerlerinin hesaplanabildiğini gösterdiği vurgulanmaktadır.',4,2),
(tid,'inference','Dalga-parçacık ikiliği deneysel olarak nasıl desteklenmektedir?','["Elektron sadece dalga özellikleri gösterir","Çift yarık deneyi elektronların girişim örüntüsü oluşturduğunu gösterir","Parçacıklar hiçbir zaman girişim göstermez","Dalga teorisi yalnızca fotonlara uygulanır"]',1,'Çift yarık deneyinde elektronlar girişim örüntüsü (dalga davranışı) oluştururken aynı zamanda ekrana tek tek nokta (parçacık davranışı) olarak çarpmaktadır.',4,3);

SELECT id INTO tid FROM text_library WHERE title='Dalga Hareketi ve Ses Fiziği';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Metnin ana konusu nedir?','["Elektromanyetik dalgalar","Ses dalgaları ile mekanik dalga hareketi","Işık yansıması","Radyo dalgalarının iletimi"]',1,'Metin mekanik dalgaların özelliklerini, ses dalgalarının boyuna dalga yapısını ve Doppler etkisini açıklamaktadır.',3,1),
(tid,'detail','Doppler etkisi hangi olguyu açıklar?','["Sesin ışıktan yavaş olduğunu","Kaynağın hareketine bağlı olarak algılanan frekans değişimini","Ses dalgalarının eğrilmesini","Ultrasonun yüksek frekanslı olduğunu"]',1,'Metinde Doppler etkisinin, ses kaynağı ile gözlemci arasındaki göreli hareketten kaynaklanan frekans kaymasını tanımladığı açıklanmaktadır.',3,2),
(tid,'inference','Ses dalgalarının vakumda yayılamaması ne anlama gelir?','["Ses ışıktan yavaştır","Ses yayılmak için maddesel bir ortama ihtiyaç duyar","Ses dalgaları elektromanyetik dalgadır","Ses yalnızca katılarda ilerler"]',1,'Ses mekanik (boyuna) dalgadır; yayılabilmek için parçacıkların sıkışıp genişleyebildiği maddesel bir ortam gerektirir. Vakumda ortam yoktur.',3,3);

SELECT id INTO tid FROM text_library WHERE title='Tanzimat Edebiyatı ve Yenilik';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metin hangi edebi ve tarihsel dönemi ele almaktadır?','["Divan edebiyatının altın çağını","1839 Tanzimat Fermanı ile başlayan Batı etkili edebiyat dönemini","Cumhuriyet''in edebi mirasını","Halk edebiyatı geleneğini"]',1,'Metin Tanzimat döneminde Batılı roman, tiyatro ve gazetecilik türlerinin Türk edebiyatına girişini ve bunun kültürel etkilerini incelemektedir.',3,1),
(tid,'detail','Tanzimat dönemi edebiyatının Osmanlı toplumuna en önemli katkısı nedir?','["Divan şiirini zirveye taşıması","Bireysel özgürlük ve toplumsal reform gibi Batılı fikirleri halka ulaştırması","Türkçeyi yabancı etkilerden arındırması","Osmanlı siyasi yapısını güçlendirmesi"]',1,'Metinde Şinasi, Namık Kemal ve Ziya Paşa gibi yazarların gazete ve edebiyat yoluyla Batılı fikirler ile reform taleplerini kamuoyuna taşıdığı belirtilmektedir.',3,2),
(tid,'inference','Tanzimat''ın Osmanlı edebiyatına etkisi hakkında ne söylenebilir?','["Etkisi yalnızca dil alanıyla sınırlı kalmıştır","Geleneksel biçimlerin yanına Batılı türler ve temalar eklenerek zenginleşme yaşanmıştır","Divan edebiyatını tamamen ortadan kaldırmıştır","Bu dönem edebi açıdan verimsizdir"]',1,'Roman, tiyatro ve gazete gibi Batılı türlerin geleneksel biçimlerle bir arada var olması Osmanlı edebiyatını çeşitlendirmiştir.',3,3);

SELECT id INTO tid FROM text_library WHERE title='Enzimler ve Metabolizma';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Metnin temel konusu nedir?','["Hormonların üretimi","Enzimlerin yapısı, çalışma mekanizması ve metabolizmadaki rolleri","Sinir sistemi iletimi","Hücre bölünmesi"]',1,'Metin enzimlerin protein yapısını, aktif bölge modelini ve metabolik yollaklardaki katalizör işlevlerini açıklamaktadır.',3,1),
(tid,'detail','Anahtar-kilit modeli enzim çalışmasında neyi açıklar?','["Enzimin enerji üretimini","Substratın spesifik aktif bölgeye tam uyumunu","Enzimin sıcaklığa duyarlılığını","Enzimin DNA''yı kopyalamasını"]',1,'Metinde anahtar-kilit modelinin substratın enzimin aktif bölgesine özgül biçimde bağlandığını ve bu spesifikliğin katalitik etkinliği sağladığını açıkladığı belirtilmektedir.',3,2),
(tid,'inference','Sıcaklık artışının enzim aktivitesi üzerindeki etkisi neden önemlidir?','["Sıcaklık enzimleri her zaman hızlandırır","Optimum üstü sıcaklıkta enzim denature olarak aktivitesini yitirebilir","Sıcaklığın enzimlerle hiç ilgisi yoktur","Düşük sıcaklıkta enzimler kalıcı olarak zarar görür"]',1,'Optimum sıcaklık üzerinde enzimin üç boyutlu yapısı bozulur (denaturasyon), aktif bölge değişir ve substrat artık bağlanamaz.',3,3);

SELECT id INTO tid FROM text_library WHERE title='Türk Edebiyatında Modernizm';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metin Türk edebiyatında hangi akımı incelemektedir?','["Romantizm","Modernizm ve bilinç akışı, iç monolog gibi teknikler","Natüralizm","Sembolizm"]',1,'Metin Türk edebiyatında modernist anlayışın 1940-1960 arası nasıl yayıldığını, başlıca temsilcilerini ve tekniklerini ele almaktadır.',3,1),
(tid,'detail','Türk edebiyatında modernizmin öne çıkan özelliklerinden biri nedir?','["Doğrusal olay örgüsüne bağlılık","Bilinç akışı ve iç monolog teknikleriyle karmaşık psikolojik iç dünyaların aktarımı","Tarihsel belgeleri düz anlatımla vermek","Halk kahramanlarını yüceltmek"]',1,'Metinde Türk modernist yazarların bilinç akışı, iç monolog ve çoğul bakış açısı gibi tekniklerle bireyin iç dünyasına odaklandığı belirtilmektedir.',3,2),
(tid,'inference','Modernist Türk romanlarının Batılı modernist anlayışla ilişkisi nasıl değerlendirilebilir?','["Batı''yı yalnızca taklit etmişlerdir","Türk toplumsal gerçekliğiyle harmanlayarak özgün bir ses oluşturmuşlardır","Tamamen bağımsız gelişmişlerdir","Yalnızca biçimsel ödünçlemeler yapmışlardır"]',1,'Oğuz Atay ve Adalet Ağaoğlu gibi yazarlar Batılı teknikleri Türk tarihsel ve toplumsal deneyimiyle kaynaştırarak özgün eserler üretmişlerdir.',3,3);

-- ══════════════════════════════════════════════════════════════
-- ALES
-- ══════════════════════════════════════════════════════════════

SELECT id INTO tid FROM text_library WHERE title='Bilimsel Düşünme ve Araştırma Metodolojisi';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metin hangi süreci açıklamaktadır?','["Felsefi düşüncenin tarihi","Bilimsel yöntem ve güvenilir bilgi üretme süreci","Sanat ve yaratıcılık metodolojisi","İstatistiksel analiz teknikleri"]',1,'Metin hipotez kurma, veri toplama, analiz ve sonuç çıkarma aşamalarından oluşan bilimsel süreci ve bu sürecin geçerlilik ölçütlerini açıklamaktadır.',4,1),
(tid,'detail','Bilimsel araştırmada kontrol grubu neden kullanılır?','["Sonuçları güzel göstermek için","Bağımsız değişkenin etkisini diğer değişkenlerden ayırt etmek için","Araştırma süresini kısaltmak için","Katılımcı sayısını azaltmak için"]',1,'Kontrol grubu, deneysel gruba uygulanmayan müdahalenin varsayılan etkisini ölçmek ve karıştırıcı değişkenleri dışlamak amacıyla kullanılır.',4,2),
(tid,'inference','Peer review (hakemli değerlendirme) süreci bilimde neden önemlidir?','["Araştırmanın maliyetini azaltır","Bağımsız uzmanların hata ve önyargıları tespit ederek bilginin kalitesini artırır","Araştırmacıların ünlenmesini sağlar","Süreci hızlandırır"]',1,'Hakemli değerlendirme, araştırmayı metodolojik açıdan bağımsız gözden geçirerek hataları ve önyargıları azaltır, böylece bilimsel bilginin kalite güvencesini sağlar.',4,3);

SELECT id INTO tid FROM text_library WHERE title='Dil Edinimi ve Evrimsel Kökenler';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metnin odak noktası nedir?','["Yabancı dil öğrenme teknikleri","Çocukların dili doğal yollarla edinme süreci ve dilin evrimi","Dilbilgisi kuralları","Alfabenin tarihi"]',1,'Metin çocuklardaki kritik dönem hipotezini, evrensel dilbilgisi tartışmasını ve dilin evrimsel kökenlerini ele almaktadır.',4,1),
(tid,'detail','Kritik dönem hipotezi dil edinimi hakkında ne öne sürer?','["Dil her yaşta eşit kolaylıkla öğrenilir","Beyin gelişiminin belirli bir döneminde ana dil edinimi çok daha kolaylaşır","Yetişkinler çocuklardan daha hızlı öğrenir","Dil öğrenimi tamamen bilinçli çabaya bağlıdır"]',1,'Kritik dönem hipotezi beynin nöroplastisitesinin yüksek olduğu erken yaşlarda dil ediniminin kolaylaştığını; bu dönem kapandıktan sonra yeni bir dili anadil düzeyinde edinmenin güçleştiğini öne sürmektedir.',4,2),
(tid,'inference','Chomsky''nin evrensel dilbilgisi teorisi dil öğrenimi hakkında ne ima eder?','["Tüm diller aynı kelime dağarcığını paylaşır","İnsanlarda doğuştan gelen dilsel bir kapasite vardır","Dil yalnızca sosyal öğrenmeyle edinilir","Her dil tamamen diğerlerinden bağımsız yapıya sahiptir"]',1,'Evrensel dilbilgisi teorisi, tüm insanların doğuştan gelen dilsel bir yapı ile doğduğunu öne sürerek dil ediniminin neden bu denli hızlı gerçekleştiğini açıklamaktadır.',4,3);

SELECT id INTO tid FROM text_library WHERE title='Yapay Zeka ve Etik Sorunlar';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metin YZ ile ilgili hangi boyutu ele almaktadır?','["YZ algoritmalarının teknik detayları","YZ sistemlerinin yol açtığı etik, önyargı ve hesap verebilirlik sorunları","YZ''nin tarihsel gelişimi","YZ donanım gereksinimleri"]',1,'Metin algoritmik önyargı, şeffaflık eksikliği, iş gücü etkisi ve sorumluluk boşluğu gibi YZ''nin toplumsal ve etik boyutlarını incelemektedir.',4,1),
(tid,'detail','Algoritmik önyargı nasıl ortaya çıkabilir?','["Yalnızca kasıtlı manipülasyonla","Önyargılı veya temsil eksikli eğitim verileri nedeniyle","Donanım yetersizlikleri yüzünden","Kullanıcı arayüzü tasarımından kaynaklanarak"]',1,'Metinde YZ modellerinin önyargılı eğitim verilerindeki kalıpları öğrenerek bu önyargıları ölçeğe taşıyabildiği ve bu durumun ayrımcılık riskini beraberinde getirdiği vurgulanmaktadır.',4,2),
(tid,'inference','YZ sistemlerinde şeffaflık neden önemlidir?','["Sistemleri daha hızlı kılar","Kullanıcıların ve denetçilerin kararları anlayıp sorgulayabilmesini sağlar","Algoritmik önyargıyı otomatik olarak ortadan kaldırır","Yalnızca araştırmacılara faydalıdır"]',1,'Kararlarının gerekçesi anlaşılamayan sistemler (kara kutu), hem hata tespitini hem de hesap verebilirliği engeller; bu nedenle şeffaflık demokratik denetim için zorunludur.',4,3);

SELECT id INTO tid FROM text_library WHERE title='Ekonomik Büyüme Teorileri';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metin ekonomide hangi konuyu incelemektedir?','["Enflasyonun nedenleri","Klasik ve içsel büyüme modelleri dahil ekonomik büyüme teorileri","Para politikasının araçları","Döviz kuru sistemleri"]',1,'Metin Solow büyüme modeli, içsel büyüme teorisi ve kurumların büyümedeki rolü gibi temel teorik yaklaşımları karşılaştırarak ele almaktadır.',4,1),
(tid,'detail','Solow modelinde uzun dönem büyüme neyle açıklanmaktadır?','["Sermaye birikimi","Teknolojik ilerleme","Nüfus büyümesi","Hükümet harcamaları"]',1,'Solow modeli sermaye birikiminin azalan getiriler nedeniyle bir denge noktasına ulaştığını; uzun vadeli kişi başı büyümenin teknolojik ilerlemeyle (dışsal) sağlanabileceğini göstermektedir.',4,2),
(tid,'inference','İçsel büyüme teorisi ne önerir?','["Büyüme tamamen dışsal faktörlerle belirlenir","Ar-Ge ve beşeri sermaye yatırımları büyümeyi içeriden besler","Devlet müdahalesi büyümeyi engeller","Büyüme yalnızca doğal kaynaklara bağlıdır"]',1,'İçsel büyüme teorisi araştırma, inovasyon ve eğitim gibi içsel faktörlerin sürdürülebilir büyüme yaratabileceğini öne sürmektedir.',4,3);

SELECT id INTO tid FROM text_library WHERE title='Sosyolojide Kimlik ve Kültür';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metnin ana teması nedir?','["Bireyin biyolojik özellikleri","Kimliğin sosyal inşası ve kültürle ilişkisi","Ekonomik sınıf yapısı","Siyasi ideolojilerin karşılaştırılması"]',1,'Metin kültürel kimliğin nasıl inşa edildiğini, küreselleşmenin bu yapıyı nasıl etkilediğini ve kimlik-kültür dinamiklerini sosyolojik perspektifle ele almaktadır.',4,1),
(tid,'detail','Kimliğin sosyal inşa olduğu görüşü ne anlama gelir?','["Kimlik tamamen genetik faktörlerle belirlenir","Kimlik, toplumsal etkileşim ve kültürel bağlam içinde şekillenir","Kimlik değişmez ve sabit bir yapıya sahiptir","Kimlik yalnızca bireysel tercihlerden oluşur"]',1,'Kimliğin sosyal inşa olması, bireyin kimliğinin toplumsal normlar, kültürel pratikler ve etkileşimler aracılığıyla zaman içinde biçimlendiğini ifade eder.',4,2),
(tid,'inference','Küreselleşme kültürel kimlikler üzerinde nasıl bir etki yaratmaktadır?','["Her kültürü izole eder","Kültürel homojenleşme ve yerel kimlik direnci gerilimini besler","Yalnızca olumlu etki yapar","Kültürel farklılıkları tamamen ortadan kaldırır"]',1,'Küresel kültürün yayılması ile yerel kimliklerin korunma çabası arasındaki gerilim, hem homojenleşme hem de kültürel direniş biçimlerini doğurmaktadır.',4,3);

SELECT id INTO tid FROM text_library WHERE title='Felsefede Bilgi Kuramı (Epistemoloji)';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metin felsefenin hangi dalını incelemektedir?','["Estetik","Bilginin doğası, kaynakları ve sınırlarını araştıran epistemoloji","Siyaset felsefesi","Mantık ve çıkarım teorisi"]',1,'Metin epistemolojinin temel sorularını, rasyonalizm ile empirizm arasındaki tartışmayı ve haklılandırılmış inancın koşullarını ele almaktadır.',5,1),
(tid,'detail','Rasyonalizm ile empirizm arasındaki temel fark nedir?','["Rasyonalizm deneyi, empirizm aklı ön plana çıkarır","Rasyonalizm bilginin akıldan geldiğini, empirizm ise duyulardan geldiğini savunur","İkisi tamamen aynı görüşü paylaşır","Rasyonalizm ahlak, empirizm ise doğa bilimleriyle ilgilenir"]',1,'Rasyonalizm (Descartes, Leibniz) a priori bilgiyi doğuştan gelen akıl ilkeleriyle, empirizm (Locke, Hume) ise duyu deneyimiyle temellendirmektedir.',5,2),
(tid,'inference','Gettier probleminin JTB (Haklılandırılmış Doğru İnanç) teorisi için önemi nedir?','["Teoriyi tamamen doğrulamaktadır","Haklılandırılmış doğru inancın bilgi için yeterli olmayabileceğini göstermiştir","Yalnızca pratik açıdan anlamsızdır","Rasyonalizmi çürütmüştür"]',1,'Gettier, şans faktörüyle haklılandırılmış doğru inancın oluşabileceği örnekler sunarak bilginin tanımı için ek koşullar gerektiğini ortaya koymuştur.',5,3);

SELECT id INTO tid FROM text_library WHERE title='Psikolojide Bilişsel Süreçler';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metnin odak noktası nedir?','["Kişilik kuramları","Dikkat, bellek ve problem çözme gibi bilişsel süreçler","Sosyal davranış ve uyum","Duygu ve motivasyon teorileri"]',1,'Metin bilişsel psikolojinin temel ilgi alanı olan zihinsel bilgi işleme süreçlerini (algı, dikkat, bellek, dil, karar verme) ele almaktadır.',4,1),
(tid,'detail','Çalışma belleği neden önemlidir?','["Uzun süreli anıları depolar","Anlık bilgi işleme ve problem çözme için geçici depolama sağlar","Duyguları düzenler","Yalnızca dil süreçlerinde rol oynar"]',1,'Metinde çalışma belleğinin aktif zihinsel görevler için bilgiyi geçici olarak tutup işlediği; yürütücü işlevlerin merkezi olduğu vurgulanmaktadır.',4,2),
(tid,'inference','Bilişsel önyargılar karar verme sürecini nasıl etkileyebilir?','["Her zaman doğru karara götürür","Sistematik hatalar yaratarak gerçekçi olmayan değerlendirmelere yol açabilir","Yalnızca duygusal kararlarda devreye girer","Deneyim arttıkça tamamen ortadan kalkar"]',1,'Bilişsel önyargılar akıl yürütmedeki sistematik sapmalardır; hem bireysel hem de kolektif düzeyde hatalı karar ve yargılara zemin hazırlayabilir.',4,3);

SELECT id INTO tid FROM text_library WHERE title='Küresel İklim Değişikliği';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metin iklim değişikliğini hangi boyutuyla ele almaktadır?','["Yalnızca tarihi iklim verilerini","Sera gazı emisyonlarından kaynaklanan insan yapımı iklim değişikliği, etkileri ve çözümleri","Doğal iklim döngülerini","Ozon tabakasındaki incelmeyiyi"]',1,'Metin CO2 artışı, sera etkisi, buzul erimesi, deniz seviyesi ve çözüm stratejileri (yenilenebilir enerji, Paris Anlaşması) gibi konuları kapsamlı biçimde ele almaktadır.',3,1),
(tid,'detail','Küresel ısınmanın öncelikli nedeni nedir?','["Güneş aktivitesindeki artış","Fosil yakıt kullanımından kaynaklanan CO2 ve sera gazı birikimi","Volkanik patlamalar","Ormansızlaşma yoluyla artan su buharı"]',1,'Metinde 20. yüzyıldan itibaren gözlemlenen hızlı ısınmanın fosil yakıt kaynaklı sera gazı artışıyla güçlü biçimde ilişkili olduğu bilimsel uzlaşıya dayandırılarak açıklanmaktadır.',3,2),
(tid,'inference','İklim değişikliğiyle mücadelede uluslararası işbirliği neden zorunludur?','["Her ülke kendi topraklarında yeterli önlemi alabilir","Emisyonlar sınır tanımaz ve etkiler küreseldir","Gelişmekte olan ülkeler bu süreçten muaf tutulmalıdır","Teknoloji transferi dışında başka çözüm yoktur"]',1,'Sera gazları atmosferde ulusal sınırları aşarak biriktiğinden ve etkiler tüm dünyayı kapsadığından ancak küresel işbirliğiyle etkili mücadele mümkündür.',3,3);

SELECT id INTO tid FROM text_library WHERE title='Nörobilim ve Bilinç';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metnin temel konusu nedir?','["Davranışsal psikoloji","Beyin yapısı, nöral ağlar ve bilincin nörobilimsel açıklamaları","Hormonlar ve biyokimya","Genetik ve kalıtım"]',1,'Metin nörobilimin bilinç, benlik bilinci ve zihin-beden ilişkisini araştırma biçimlerini ele almaktadır.',5,1),
(tid,'detail','Zor bilinç problemi neyi sorgulamaktadır?','["Beynin fiziksel boyutunu","Nöral süreçlerin sübjektif deneyimi (qualia) nasıl yarattığını","Belleğin nerede depolandığını","Bilinçdışı süreçlerin davranışa etkisini"]',1,'David Chalmers''ın tanımladığı zor problem, fiziksel beyin süreçleri ile kişisel deneyim arasındaki açıklanamayan boşluğu (explanatory gap) sorgular.',5,2),
(tid,'inference','Nöroplastisite bulgusu öğrenme hakkında ne çıkarımını güçlendirir?','["Beyin yetişkinlikte değişmez","Yaşam boyu deneyim ve öğrenmeyle beyin bağlantıları yeniden biçimlenir","Zeka tamamen kalıtsaldır","Yeni beceriler yalnızca gençlikte edinilebilir"]',1,'Nöroplastisite, beynin deneyime yanıt olarak yapısal ve işlevsel değişiklikler geçirdiğini ortaya koyar; bu da yaşam boyu öğrenmenin biyolojik temelini açıklar.',4,3);

SELECT id INTO tid FROM text_library WHERE title='İstatistiksel Analizde Temel Kavramlar';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Metinde hangi bilimsel araç tanıtılmaktadır?','["Matematiksel ispat yöntemleri","Verileri yorumlamaya yarayan istatistiksel kavramlar ve yöntemler","Algoritma tasarımı","Mantıksal çıkarım kuralları"]',1,'Metin merkezi eğilim ölçümleri, varyans, hipotez testi ve güven aralıkları gibi temel istatistik kavramlarını araştırma bağlamında açıklamaktadır.',4,1),
(tid,'detail','P değeri hipotez testinde ne anlama gelir?','["Etki büyüklüğünü gösterir","Sıfır hipotezi doğruyken gözlemlenen sonuç kadar uç bir sonuç elde etme olasılığını ifade eder","Örneklem büyüklüğünü belirtir","Değişkenler arasındaki korelasyonu ölçer"]',1,'Metinde p değerinin sıfır hipotezi doğruyken gözlenen verilerin şansa ne kadar atfedilebileceğini gösterdiği açıklanmaktadır.',4,2),
(tid,'inference','Korelasyonun nedensellik anlamına gelmemesi araştırma için neden önemlidir?','["İstatistiğin güvenilirliğini zayıflatır","İlişkiyi doğrudan nedensellikle yorumlamaktan kaçınmak gerektirir","Deneysel araştırmaları gereksiz kılar","Yalnızca sosyal bilimlerde geçerlidir"]',1,'İki değişken arasındaki korelasyon, karıştırıcı değişkenler ya da ters nedensellik nedeniyle yanıltıcı olabilir; nedensellik için kontrollü deneyler gerekir.',4,3);

-- ══════════════════════════════════════════════════════════════
-- KPSS
-- ══════════════════════════════════════════════════════════════

SELECT id INTO tid FROM text_library WHERE title='Atatürk''ün Eğitim Reformları';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metin Türkiye''de hangi alandaki dönüşümü ele almaktadır?','["Ekonomik reformları","Atatürk döneminde laik ve millî eğitim sisteminin inşasını","Osmanlı eğitim anlayışını","Siyasi parti yapılanmasını"]',1,'Metin öğretim birliği, harf devrimi ve yüksek öğretim reformlarıyla şekillenen eğitim devrimini ele almaktadır.',2,1),
(tid,'detail','1924 tarihli Tevhid-i Tedrisat Kanunu''nun amacı nedir?','["Medreseleri modernize etmek","Tüm eğitim kurumlarını tek çatı altında toplayarak din ve devlet eğitimini birleştirmek","Eğitimi laikleştirmek amacıyla tüm okulları Millî Eğitim Bakanlığı''na bağlamak","Sadece kız okulları açmak"]',2,'Metinde Tevhid-i Tedrisat Kanunu''nun okul türlerini birleştirerek eğitimde laikliğin ve ulusal müfredatın temelini attığı belirtilmektedir.',2,2),
(tid,'inference','Harf devriminin eğitime katkısı neden kritik görülmektedir?','["Yalnızca estetik bir değişiklik getirmiştir","Latin alfabesi okuma-yazmayı kolaylaştırarak okuryazarlık oranını artırmıştır","Osmanlı kaynaklarına erişimi kolaylaştırmıştır","Türkçenin sözlü geleneğini dönüştürmüştür"]',1,'Latin alfabesine geçiş Arap harflerine kıyasla öğrenimi hızlandırmış ve okuryazarlığı artırarak Cumhuriyet''in eğitim hedeflerine doğrudan katkı sağlamıştır.',2,3);

SELECT id INTO tid FROM text_library WHERE title='Türkiye''nin Anayasal Düzeni';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metinde hangi konu ele alınmaktadır?','["Türkiye''nin ekonomik yapısı","Türkiye Cumhuriyeti Anayasası''nın ilkeleri ve yapısı","Dış politika öncelikleri","Seçim sistemi uygulamaları"]',1,'Metin Türkiye''nin anayasal yapısını, temel ilkeleri (laiklik, cumhuriyetçilik vb.) ve güçler ayrılığını ele almaktadır.',2,1),
(tid,'detail','Türkiye Cumhuriyeti Anayasası''nın temel niteliklerinden biri nedir?','["Federalist devlet yapısı","Laik, demokratik, sosyal hukuk devleti ilkeleri","Çift meclisli yapı","Monarşik unsurlar"]',1,'Metinde anayasanın Türkiye''yi demokratik, laik ve sosyal bir hukuk devleti olarak tanımladığı belirtilmektedir.',2,2),
(tid,'inference','Anayasal güvenceler bireyler için neden önemlidir?','["Yalnızca devlet kurumlarını düzenler","Temel hak ve özgürlükleri koruyarak devlet gücünü sınırlar","Ekonomik kalkınmayı sağlar","Dış politikayı yönlendirir"]',1,'Anayasal güvenceler, devlet gücünün keyfi kullanımını önleyerek bireysel hak ve özgürlüklerin sürdürülebilir biçimde korunmasını sağlar.',2,3);

SELECT id INTO tid FROM text_library WHERE title='Millî Mücadele Dönemi ve Kurtuluş Savaşı';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Metin hangi tarihsel dönemi ele almaktadır?','["Osmanlı''nın kuruluş dönemi","Birinci Dünya Savaşı sonrasında yaşanan Millî Mücadele ve Kurtuluş Savaşı","Tanzimat reformları dönemi","İkinci Dünya Savaşı dönemi"]',1,'Metin 1919-1923 yılları arasında Mustafa Kemal''in önderliğinde verilen Millî Mücadele sürecini ve Türkiye Cumhuriyeti''nin kuruluşunu anlatmaktadır.',2,1),
(tid,'detail','Sivas Kongresi''nin önemi nedir?','["Osmanlı padişahına bağlılığı pekiştirmiştir","Millî direnişi tek çatı altında toplayarak ulusal birliği ilan etmiştir","Müttefiklerle barış görüşmelerini başlatmıştır","Yalnızca bölgesel bir toplantı olmuştur"]',1,'Metinde Sivas Kongresi''nin tüm direniş örgütlerini birleştirip merkezi liderliği pekiştirerek millî kurtuluş mücadelesine ivme kazandırdığı belirtilmektedir.',2,2),
(tid,'inference','Kurtuluş Savaşı''nın Türkiye''nin geleceği için taşıdığı anlam nedir?','["Yalnızca askeri bir zaferdir","Hem toprak bütünlüğünü hem de Cumhuriyet''in kurucu temelini oluşturmuştur","Yalnızca bir tarafın katkısıyla gerçekleşmiştir","Türkiye''nin dış politikasını olumsuz etkilemiştir"]',1,'Kurtuluş Savaşı toprak bütünlüğünü sağladığı gibi 1923''te Türkiye Cumhuriyeti''nin kuruluşunun da zeminini hazırlamış; böylece hem askeri hem de siyasi boyutuyla belirleyici bir dönüm noktası olmuştur.',2,3);

SELECT id INTO tid FROM text_library WHERE title='Osmanlı Millet Sistemi';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metin hangi Osmanlı kurumunu incelemektedir?','["Tımar sistemi","Farklı dini ve etnik toplulukları yöneten Osmanlı millet sistemi","Yeniçeri ocağını","Divan-ı Hümayun''u"]',1,'Metin Osmanlı''nın Müslüman olmayan toplulukları kendi iç hukukları ve kurumlarıyla yönetmesini sağlayan millet sistemini ele almaktadır.',2,1),
(tid,'detail','Millet sisteminin temel özelliği nedir?','["Tüm tebaanın tek bir hukuka tabi olması","Dini toplulukların kendi iç işlerinde özerklikle yönetilmesi","Yalnızca Müslümanların hukuki güvenceye kavuşması","Merkezi bir eğitim müfredatının uygulanması"]',1,'Metinde millet sisteminin her dini topluluğun (Rum, Ermeni, Yahudi vb.) kendi liderliği ve hukuku çerçevesinde özerk biçimde yönetilmesine olanak tanıdığı açıklanmaktadır.',2,2),
(tid,'inference','Millet sistemi Osmanlı devlet anlayışı hakkında ne yansıtmaktadır?','["Dini homojenliği zorunlu kılan baskıcı bir yapıyı","Çeşitlilik içinde idari esnekliği esas alan pratik bir yönetim anlayışını","Tam anlamıyla eşitlikçi bir toplumu","Merkeziyetçi bir laikliği"]',1,'Sistem, farklı toplulukların özerkliğini korumasına olanak tanıyarak Osmanlı''nın çok dinli ve çok kültürlü yapısını yönetmeye yönelik pragmatik bir tutumu yansıtmaktadır.',3,3);

SELECT id INTO tid FROM text_library WHERE title='Türkiye''nin Ekonomik Kalkınma Süreci';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Metin hangi ekonomik süreci ele almaktadır?','["Osmanlı ekonomisini","Türkiye''nin Cumhuriyet''ten günümüze uzanan ekonomik dönüşümünü","Küresel ticaret sistemini","AB ekonomi politikalarını"]',1,'Metin devletçi sanayileşmeden liberalleşmeye, tarım toplumundan sanayi ve hizmet ekonomisine uzanan dönüşümü ele almaktadır.',2,1),
(tid,'detail','1980 sonrası Türkiye ekonomisinde yaşanan temel değişim nedir?','["Tarım sektörünün güçlenmesi","Planlı ekonomiden piyasa odaklı liberalleşmeye geçiş","Kamu sanayiinin genişlemesi","Dış ticaretin kısıtlanması"]',1,'Metinde 1980 sonrası ithal ikameci politikalardan dışa açık, serbest piyasa odaklı bir modele geçildiği vurgulanmaktadır.',2,2),
(tid,'inference','Türkiye''nin sanayileşmesindeki devlet müdahalesi hangi görüşü destekler?','["Kalkınma için devletin tamamen dışlanması gerekir","Devletin stratejik sektörleri yönlendirme rolü kalkınma sürecini hızlandırabilir","Özel sektör kalkınmada tamamen etkisizdir","Tarım kalkınmanın öncelikli motoru olmalıdır"]',1,'KİT''ler aracılığıyla devlet öncülüğünde yürütülen sanayileşme deneyimi, stratejik alanlarda devlet müdahalesinin kalkınmayı hızlandırabileceğini gösteren bir örnek oluşturmaktadır.',3,3);

SELECT id INTO tid FROM text_library WHERE title='Türkiye''de Demokratikleşme Süreci';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metin Türkiye''de hangi süreci incelemektedir?','["Ekonomik liberalleşme","Tek parti döneminden çoğulcu siyasete geçişi ve demokratikleşme aşamalarını","Anayasa yapım sürecini","Dış politikanın gelişimini"]',1,'Metin 1946''da çok partili hayata geçişten günümüze uzanan demokratikleşme sürecini kırılma noktaları ve reformlarla birlikte ele almaktadır.',2,1),
(tid,'detail','Türkiye''de çok partili siyasi hayata geçiş hangi yılda gerçekleşmiştir?','["1923","1938","1946","1960"]',2,'Metinde CHP''nin tek parti döneminin ardından 1946''da çok partili sisteme geçildiği ve 1950''de DP''nin iktidara gelmesiyle sürecin pekiştiği belirtilmektedir.',2,2),
(tid,'inference','Türkiye''nin demokratikleşme süreci genel olarak nasıl değerlendirilebilir?','["Kesintisiz ve düzgün bir ilerleme göstermiştir","Askeri müdahale ve reform dönemleri biçiminde dalgalı bir seyir izlemiştir","Yalnızca dış baskıların sonucunda ilerlemiştir","Demokratikleşme henüz başlamamıştır"]',1,'1960, 1971 ve 1980 askeri müdahaleleri ile akabindeki reform süreçleri, sürecin doğrusal değil ileriye-geri hamleli bir seyir izlediğini göstermektedir.',3,3);

SELECT id INTO tid FROM text_library WHERE title='Türkiye''nin Dış Politikası';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metin hangi konuyu ele almaktadır?','["Türkiye''nin iç siyasetini","Türkiye''nin temel dış politika önceliklerini ve tarihsel gelişimini","Türkiye''nin ekonomik ilişkilerini","Türkiye''nin kültür diplomasisini"]',1,'Metin Batı ittifaklarından bölgesel güç hedefine uzanan Türk dış politikasının temel eksenlerini ve dönüşümünü ele almaktadır.',2,1),
(tid,'detail','Türkiye''nin NATO üyeliğinin dış politikasına katkısı nedir?','["Türkiye''yi bağımsız bir aktör olmaktan çıkarmıştır","Batı savunma çerçevesi içinde güvenlik güvenceleri sağlamıştır","Türkiye''yi Ortadoğu''dan soyutlamıştır","Yalnızca ekonomik faydalar getirmiştir"]',1,'Metinde NATO üyeliğinin Türkiye''ye Soğuk Savaş döneminde Sovyet tehdidine karşı güvenlik şemsiyesi sağladığı ve dış politikasını Batı ekseninde konumlandırdığı belirtilmektedir.',2,2),
(tid,'inference','Türkiye''nin stratejik coğrafyası dış politikasını nasıl etkilemektedir?','["Yalnızca kara sınırlarını belirler","Hem Doğu hem Batı ile ilişkilerde çok boyutlu bir denge politikasını zorunlu kılar","Ekonomik kalkınmayı sınırlar","Dış politikada tekil bir ittifaka yöneltir"]',1,'Türkiye''nin Avrupa, Orta Doğu ve Orta Asya arasındaki köprü konumu, farklı taraflarla çok yönlü dengeli ilişkiler yürütmeyi dış politikasının zorunlu bir özelliği hâline getirmektedir.',3,3);

SELECT id INTO tid FROM text_library WHERE title='Anadolu''nun Coğrafi Özellikleri';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Metnin ana konusu nedir?','["Türkiye''nin nüfus yapısı","Anadolu''nun fiziki coğrafi özellikler ve bu özelliklerin insan yaşamına etkileri","Karadeniz''in deniz biyolojisi","Türkiye''nin iklim politikaları"]',1,'Metin Anadolu yarımadasının dağlık yapısını, akarsu havzalarını, iklim çeşitliliğini ve bunların tarım ile yerleşim üzerindeki etkilerini ele almaktadır.',2,1),
(tid,'detail','Anadolu''yu çevreleyen üç deniz hangisidir?','["Akdeniz, Kızıldeniz, Hazar","Karadeniz, Ege, Akdeniz","Marmara, Adriyatik, Kızıldeniz","Hazar, Basra Körfezi, Karadeniz"]',1,'Metinde Anadolu''nun kuzeyinde Karadeniz, batısında Ege ve güneyinde Akdeniz ile çevrili olduğu belirtilmektedir.',2,2),
(tid,'inference','Anadolu''nun dağlık yapısı tarih boyunca nasıl bir etki yaratmıştır?','["Ticareti kolaylaştırmıştır","Geçit bölgelerini stratejik değer taşıyan noktalara dönüştürmüştür","Nüfusu tek bir bölgede yoğunlaştırmıştır","Tarımsal verimliliği artırmıştır"]',1,'Dağ geçitlerinin kontrolü tarihsel açıdan ticaret yolları ve askeri hâkimiyet için belirleyici olmuştur; bu bağlamda Anadolu''nun dağlık yapısı stratejik bir değer kazanmıştır.',2,3);

SELECT id INTO tid FROM text_library WHERE title='İnsan Hakları ve Türkiye';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metin ne hakkındadır?','["Türkiye''nin ekonomik yükümlülükleri","İnsan hakları normlarının uluslararası hukuki temeli ve Türkiye''deki uygulaması","AB üyelik müzakereleri","Türkiye''nin çevre politikaları"]',1,'Metin İHEB''den AİHM''e uzanan uluslararası insan hakları sistemini ve bu standartların Türkiye''deki hayata geçirilmesini ele almaktadır.',2,1),
(tid,'detail','1948 İnsan Hakları Evrensel Beyannamesi''nin önemi nedir?','["Yalnızca Avrupa ülkeleri için bağlayıcıdır","Uluslararası düzeyde temel hak ve özgürlüklerin evrensel standartını belirlemiştir","Askeri müdahaleye onay vermiştir","Yalnızca ekonomik hakları güvence altına almıştır"]',1,'Metinde İHEB''in tüm insanlığa uygulanabilir evrensel haklar çerçevesi oluşturduğu ve modern insan hakları hukukunun temeli sayıldığı belirtilmektedir.',2,2),
(tid,'inference','AİHM kararlarının Türkiye''deki önemi nedir?','["Yalnızca para cezası içerir","İç hukuk uygulamalarını Avrupa insan hakları standartlarıyla hizalamada baskı aracı işlevi görür","Türkiye''nin iç işlerine karışma sayılır","Türkiye için bağlayıcı değildir"]',1,'AİHM kararları taraf devletleri hukuki reformlara yönlendiren ve iç uygulamaların Avrupa standartlarıyla örtüşmesini sağlayan bir denetim mekanizması oluşturmaktadır.',2,3);

SELECT id INTO tid FROM text_library WHERE title='İkinci Dünya Savaşı ve Türkiye';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metin İkinci Dünya Savaşı döneminde Türkiye''yi hangi açıdan ele almaktadır?','["Türkiye''nin askeri katılımını","Türkiye''nin tarafsızlık politikasını ve savaşın yansımalarını","Türkiye''nin müttefiklerle askeri iş birliğini","Türkiye''nin toprak kayıplarını"]',1,'Metin Türkiye''nin savaş boyunca izlediği dikkatli tarafsızlık politikasını, ekonomik zorlukları ve savaş sonrası uluslararası sisteme entegrasyonunu ele almaktadır.',2,1),
(tid,'detail','Türkiye''nin İkinci Dünya Savaşı''ndaki tutumu nasıl tanımlanabilir?','["Mihver güçlerinin müttefiki","Müttefiklerin aktif destekçisi","Diplomatik tarafsızlık politikası","İşgale uğrayan taraf"]',2,'Metinde Türkiye''nin savaş boyunca doğrudan çatışmaya girmeden her iki bloğa da belirli düzeyde ilişki kurarak ihtiyatlı bir tarafsızlık politikası izlediği belirtilmektedir.',2,2),
(tid,'inference','Türkiye''nin BM''ye kurucu üye olması ve ardından NATO''ya katılması ne anlama gelir?','["Tarafsızlık politikasının sürdürüldüğünü","Savaş sonrasında Batı ittifak sistemine ve kolektif güvenliğe yöneldiğini","Soğuk Savaş''tan bağımsız kaldığını","Yalnızca BM''yi tercih ettiğini"]',1,'BM üyeliği ve NATO''ya katılım, Türkiye''nin savaş sonrasında Batılı kolektif güvenlik mimarisine entegrasyonunu simgelemektedir.',2,3);

-- ══════════════════════════════════════════════════════════════
-- GENERAL
-- ══════════════════════════════════════════════════════════════

SELECT id INTO tid FROM text_library WHERE title='Uzay Keşfinin Geleceği';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metnin odak noktası nedir?','["Antik astronominin tarihi","Özel şirketlerin katılımı ve Mars hedefleri dahil modern uzay keşfinin geleceği","Güneş Sistemi''nin oluşumu","Uzayda yaşam aramak"]',1,'Metin özel sektörün uzay sektörüne girişini, Artemis programını, Mars hedeflerini ve James Webb Teleskobu''nun bulgularını ele almaktadır.',2,1),
(tid,'detail','James Webb Uzay Teleskobu''nun bilime temel katkısı nedir?','["Yalnızca Güneş''i incelemek","Erken evren galaksilerini ve öte gezegen atmosferlerini benzeri görülmemiş ayrıntıyla görüntülemek","Mars yüzeyini haritalandırmak","Uzay istasyonlarını denetlemek"]',1,'Metinde James Webb''in daha önce ulaşılamayan erken evren galaksilerini ve öte gezegen atmosferlerini yüksek çözünürlüklü görüntülerle ortaya koyduğu belirtilmektedir.',2,2),
(tid,'inference','Özel şirketlerin uzay sektörüne girmesi ne anlama gelmektedir?','["Devlet ajanslarının artık gerekli olmadığını","Rekabet ve inovasyon sayesinde maliyetlerin düştüğünü ve erişimin genişlediğini","Uzay keşfinin tehlikeli hâle geldiğini","Uzayın ticarileşmesinin bilimsel araştırmayı sekteye uğrattığını"]',1,'SpaceX ve Blue Origin gibi şirketlerin yeniden kullanılabilir roket teknolojisiyle fırlatma maliyetlerini dramatik biçimde düşürdüğü ve böylece uzay erişimini demokratikleştirdiği metinden anlaşılmaktadır.',2,3);

SELECT id INTO tid FROM text_library WHERE title='Meditasyonun Beyne Etkisi';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metnin temel konusu nedir?','["Nefes egzersizleri","Düzenli meditasyonun beyin yapısı ve zihinsel sağlık üzerindeki bilimsel kanıta dayalı etkileri","Yoga ve fiziksel egzersiz","Uyku kalitesinin iyileştirilmesi"]',1,'Metin meditasyonun amigdala, prefrontal korteks ve kortizol düzeyleri üzerindeki ölçülmüş etkilerini nörobilimsel kanıtlarla açıklamaktadır.',2,1),
(tid,'detail','Düzenli meditasyon beyin yapısını nasıl etkilemektedir?','["Beyni küçültür","Amigdalayı küçültürken prefrontal korteksi geliştirir","Kortizol üretimini artırır","Beyin fonksiyonları üzerinde kalıcı etkisi yoktur"]',1,'Metinde meditasyonun korku ve kaygıyla ilişkili amigdalanın hacmini azaltırken karar alma ve duygusal düzenlemeyle bağlantılı prefrontal korteksi güçlendirdiği belirtilmektedir.',2,2),
(tid,'inference','MBCT''nin (Farkındalığa Dayalı Bilişsel Terapi) klinik kılavuzlara girmesi ne anlama gelir?','["Meditasyon bilimsel olarak yararsız bulunmuştur","Meditasyon temelli yaklaşımlar klinik kılavuzlarda yer alacak düzeyde kanıt gücüne ulaşmıştır","Meditasyon yalnızca alternatif tıp alanında kullanılmaktadır","Tüm ruhsal rahatsızlıklar meditasyonla tedavi edilebilir"]',1,'MBCT''nin kılavuzlara girmesi, meditasyonun randomize kontrollü çalışmalarla desteklenen klinik etkinliğini kanıtlamaktadır.',2,3);

SELECT id INTO tid FROM text_library WHERE title='Türk Mutfağının Zengin Tarihi';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metin ne hakkındadır?','["Türk mutfağındaki bir yemeğin tarifi","Türk mutfağının tarihsel köklerini ve bölgesel çeşitliliğini","Türkiye''nin tarım politikasını","Osmanlı sarayının mimari özelliklerini"]',1,'Metin Orta Asya''dan Osmanlı sarayına uzanan Türk mutfağının tarihsel evrimini, coğrafi çeşitliliğini ve kültürel önemini ele almaktadır.',1,1),
(tid,'detail','Türk kahvesi ve çay kültürünün önemi nedir?','["Yalnızca birer içecektir","UNESCO listesinde yer alan bir kültürel miras öğesi olarak toplumsal bağları güçleştirir","Ekonomik açıdan önemsizdir","Yalnızca İstanbul''a özgüdür"]',1,'Metinde Türk kahvesi kültürünün UNESCO Somut Olmayan Kültürel Miras listesinde yer aldığı ve toplumsal ilişkilerin pekiştirilmesinde kritik bir rol oynadığı vurgulanmaktadır.',1,2),
(tid,'inference','Türk mutfağının bölgeden bölgeye farklılaşması neyi yansıtmaktadır?','["Mutfak standardizasyonunu","Coğrafi ve kültürel çeşitlilikle şekillenen zengin bir mirası","Tarihsel izolasyonu","Yalnızca iklim farklılıklarını"]',1,'Orta Asya göçebelerinden Osmanlı saray kültürüne, Ege''den İç Anadolu''ya uzanan farklı etkilerin sentezi, Türk mutfağının bölgesel çeşitliliğinin temel kaynağıdır.',1,3);

SELECT id INTO tid FROM text_library WHERE title='Dijital Çağda Mahremiyet';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Metnin odaklandığı temel sorun nedir?','["İnternet altyapısı","Dijital çağda kişisel veri mahremiyetine ilişkin endişeler ve hukuki çerçeveler","Sosyal medya platformlarının geliri","Yapay zekanın geleceği"]',1,'Metin dijital izlerin birikmesini, veri profilleme tehlikelerini ve GDPR ile KVKK gibi yasal çerçeveleri ele almaktadır.',2,1),
(tid,'detail','GDPR bireylere hangi temel hakkı tanımaktadır?','["İnternete erişim hakkı","Kişisel verilerine erişme, silinmesini talep etme ve taşınabilirlik hakkı","Sınırsız veri paylaşım hakkı","Yalnızca kamu kurumlarından veri talep etme hakkı"]',1,'Metinde GDPR''ın erişim hakkı, unutulma hakkı ve veri taşınabilirliğini kapsayan kapsamlı bir bireysel haklar çerçevesi sunduğu belirtilmektedir.',2,2),
(tid,'inference','Cambridge Analytica skandalı ne tür bir risk olduğunu ortaya koymuştur?','["Güvenli veri depolamanın önemi","Kişisel verilerin siyasi manipülasyon ve kamuoyunu etkileme amacıyla kötüye kullanılabileceği","Sosyal medyanın ekonomik değerini","İnternet altyapısının güvenlik açıklarını"]',1,'Skandal, büyük ölçekli kişisel verilerin bireylerin onayı olmaksızın siyasi amaçlarla kullanılabileceğini gözler önüne sermiştir.',2,3);

SELECT id INTO tid FROM text_library WHERE title='Yapay Zeka Günlük Hayatı Nasıl Değiştiriyor?';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metnin temel konusu nedir?','["Yapay zekanın tarihi","YZ''nin sağlık, eğitim ve iş dünyasındaki gündelik yaşama dönüştürücü etkisi","Robotik sistemlerin teknik yapısı","YZ''nin askeri uygulamaları"]',1,'Metin YZ''nin sağlıkta teşhis, eğitimde kişiselleştirme ve iş gücü dönüşümü gibi somut etkilerini ele almaktadır.',2,1),
(tid,'detail','Sağlık alanında YZ''nin radyolojiye katkısı nedir?','["Ameliyatları otomatikleştirmek","Görüntülerde ince patolojileri tespit ederek doktorların teşhis kapasitesini artırmak","Tıp eğitimini yeniden yapılandırmak","Hastaları doğrudan tedavi etmek"]',1,'Metinde YZ radyoloji görüntülerini tarayarak doktorların gözden kaçırabileceği küçük anormallikleri tespit edebildiği için teşhis sürecini desteklediği belirtilmektedir.',2,2),
(tid,'inference','İş gücü dönüşümü açısından YZ''nin yaratıcı ve duygusal zeka gerektiren meslekler üzerindeki etkisi nasıl değerlendirilebilir?','["Bu meslekler de hızla ortadan kalkacaktır","Rutin görevlere kıyasla bu meslekler otomasyona daha dirençlidir","YZ bu meslekler için herhangi bir fırsat yaratmaz","Yaratıcı meslekler YZ''den en çok zarar görenlerdir"]',1,'Metinde yaratıcılık, eleştirel düşünme ve duygusal zeka içeren mesleklerin YZ otomasyonuna karşı daha dirençli olduğu, dolayısıyla bu alanlarda iş gücüne olan talebin süreceği vurgulanmaktadır.',2,3);

SELECT id INTO tid FROM text_library WHERE title='Okyanusların Gizemli Derinlikleri';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metnin temel konusu nedir?','["Deniz taşımacılığı","Derin okyanus ekosistemlerinin keşfedilmemiş yapısı ve iklim düzenlemesindeki rolü","Balıkçılık endüstrisi","Okyanus kirliliği ve çözümleri"]',1,'Metin okyanusların keşfedilmemiş derinliklerini, hidrotermik bacaların eşsiz ekosistemlerini ve okyanusların küresel iklim sistemindeki düzenleyici işlevini ele almaktadır.',2,1),
(tid,'detail','Hidrotermik bacalar hangi açıdan bilim dünyasında devrim niteliğindedir?','["Okyanus akıntılarını düzenlemeleri","Güneş ışığı olmadan yalnızca kimyasal enerjiyle beslenen yaşam formlarını barındırmaları","Deniz tabanında mineral kaynakları oluşturmaları","Plaka tektoniğini hızlandırmaları"]',1,'Metinde hidrotermik bacaların fotosentez yerine kemotrofik enerji kullanan canlıları barındırarak yaşamın ışık ve oksijenin olmadığı ortamlarda da sürdürülebileceğini kanıtladığı vurgulanmaktadır.',2,2),
(tid,'inference','Okyanus asitliğindeki artışın mercanlar üzerindeki etkisi neden endişe vericidir?','["Mercanlar asidik suya uyum sağlayabilir","Karbonatlı iskeletlerini çözen asit, mercan ölümlerine yol açabilir","Bu etki yalnızca derin sularda görülür","Asit artışı mercan çeşitliliğini artırır"]',1,'Artan CO2 emilimi deniz suyunu asitlendirir; bu durum mercanların CaCO3 iskeletlerini çözerek resif ekosistemlerini ciddi biçimde tehdit eder.',2,3);

SELECT id INTO tid FROM text_library WHERE title='Müziğin Psikolojik Etkileri';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metnin temel konusu nedir?','["Müziğin tarihsel gelişimi","Müziğin beyin, duygular, sağlık ve öğrenme üzerindeki psikolojik ve nörolojik etkileri","Müzik teorisi","Enstrümanların fiziksel yapısı"]',1,'Metin müziğin dopamin salgısı, terapi uygulamaları ve bilişsel gelişime katkıları gibi kanıtlanmış etkilerini ele almaktadır.',2,1),
(tid,'detail','Müzik terapinin Alzheimer hastalarına en belirgin katkısı nedir?','["Fiziksel iyileşmeyi hızlandırmak","Gençliğe ait uzun süreli anıları yüzeye çıkarmasına yardımcı olmak","Ağrıyı tamamen ortadan kaldırmak","Hastalığın ilerleme hızını durdurmak"]',1,'Metinde pek çok anısını yitirmiş Alzheimer hastalarının bile gençliklerinde sevdikleri şarkıları çoğunlukla hatırlayabildiği, müzik hafızasının duygusal bellek sistemleriyle güçlü bağ kurduğu belirtilmektedir.',2,2),
(tid,'inference','Müzik eğitiminin çocuklarda dil ve matematik becerilerini desteklediği nasıl açıklanabilir?','["Müzik ve dil beynin tamamen farklı bölgelerinde işlenir","Ritim, melodi ve matematiksel örüntüler benzer bilişsel süreçleri etkinleştirir","Müzik eğitimi yalnızca duygusal gelişimi etkiler","Bu ilişki bilimsel olarak kanıtlanmamıştır"]',1,'Metinde müzik eğitiminin dil, matematik ve yürütücü işlevleri geliştirdiğine dair güçlü kanıtların bulunduğu belirtilmektedir; bu durum müzik ile diğer bilişsel süreçler arasındaki sinirsel örtüşmeyle açıklanabilir.',2,3);

SELECT id INTO tid FROM text_library WHERE title='Yeşil Enerji ve Sürdürülebilir Gelecek';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metnin ana konusu nedir?','["Petrol ve gaz çıkarma teknolojileri","Güneş ve rüzgar gibi yenilenebilir enerji kaynaklarına geçişin gerekliliği ve olanakları","Nükleer enerji","Elektrikli araçların gelişimi"]',1,'Metin yenilenebilir enerjinin maliyet düşüşlerini, enerji depolama zorluklarını ve sürdürülebilir bir geleceğe geçişin yollarını ele almaktadır.',2,1),
(tid,'detail','Güneş enerjisinin son yıllarda yaygınlaşmasının temel nedeni nedir?','["Panel verimliliği azalmıştır","Üretim maliyetlerinin dramatik biçimde düşmesi onu pek çok bölgede rekabetçi kılmıştır","Güneş panelleri artık tüm iklim koşullarında çalışmaktadır","Hükümet destekleri verimliliği gereksiz kılmıştır"]',1,'Metinde güneş paneli maliyetlerinin on yıllar içinde dramatik biçimde gerilediği ve bu düşüşün güneş enerjisini pek çok bölgede fosil yakıtlara kıyasla ekonomik açıdan rekabetçi hâle getirdiği belirtilmektedir.',2,2),
(tid,'inference','Yenilenebilir enerjinin önündeki en büyük teknik engel nedir?','["Yeterli güneş ve rüzgar potansiyelinin bulunmaması","Güvenilir depolama ve şebeke entegrasyonu sağlamak","Kamuoyunun yenilenebilir enerjiye karşı çıkması","Yenilenebilir enerji santrallerinin aşırı büyüklüğü"]',1,'Metinde depolama teknolojisi ve akıllı ızgara entegrasyonunun yenilenebilir enerjinin kesintisiz enerji talebi için gerekli güvenilirliği sağlamasındaki temel engel olduğu belirtilmektedir.',2,3);

SELECT id INTO tid FROM text_library WHERE title='Kuantum Fiziğinin Sırları';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metnin konusu nedir?','["Klasik Newtoncu mekanik","Kuantum mekaniğinin temel ilkeleri ve klasik sezgilerimizi nasıl sarstığı","Görelilik teorisi","Termodinamik yasaları"]',1,'Metin dalga-parçacık ikiliği, Heisenberg belirsizlik ilkesi ve kuantum dolanıklığı gibi kuantum mekaniğinin temel kavramlarını ele almaktadır.',3,1),
(tid,'detail','Heisenberg Belirsizlik İlkesi ne ifade eder?','["Ölçüm aletleri yetersizdir","Bir parçacığın konum ve momentumunun aynı anda kesin değerlerle belirlenmesi doğanın temel özelliği nedeniyle imkânsızdır","Parçacıklar her zaman sabit konumda bulunur","Belirsizlik yalnızca matematiksel bir soyutlamadır"]',1,'Metinde belirsizliğin teknolojik yetersizlikten değil doğanın temel yapısından kaynaklandığı vurgulanmaktadır; konum kesinleştikçe momentum belirsizleşmektedir.',3,2),
(tid,'inference','Kuantum dolanıklığı neden ""uzaktan ürkütücü etki"" olarak nitelendirilmiştir?','["Parçacıklar görünmez hâle gelir","Dolanık parçacıklar, mesafeden bağımsız olarak anlık etkilişim içinde görünmektedir","Etki yalnızca kısa mesafelerde gerçekleşir","Parçacıkların hızı ışık hızını aşmaktadır"]',1,'Einstein, yerel gerçekçilik anlayışını sarsan bu anında uzak etkilişimi ""spooky action at a distance"" diye tanımlamıştır; kuantum dolanıklığı bilginin ışık hızında iletimi olmaksızın korelasyon sağlamaktadır.',3,3);

SELECT id INTO tid FROM text_library WHERE title='Dilin Evrimi ve Geleceği';
INSERT INTO text_questions(text_id,question_type,question_text,options,correct_index,explanation,difficulty,order_index) VALUES
(tid,'main_idea','Bu metnin temel konusu nedir?','["Dil öğrenme teknikleri","Dillerin tarihsel evrimi, tehdit altındaki diller ve dijital çağın dil üzerindeki etkisi","Çevirinin matematiksel temelleri","Alfabe gelişimi"]',1,'Metin dil ailelerini, yok olma tehlikesiyle karşı karşıya kalan dilleri, Türk dillerinin yayılımını ve dijital çağın dile etkisini ele almaktadır.',3,1),
(tid,'detail','Dünyada kaç civarında dil konuşulmakta ve bunların durumu nedir?','["Yaklaşık 500 dil, hepsi güvende","Yaklaşık 7.000 dil; yüzlercesi yok olma riskiyle karşı karşıya","Yaklaşık 200 dil, tümü canlı","Yaklaşık 3.000 dil, çoğu kaybolmuş"]',1,'Metinde dünyada yaklaşık 7.000 dil konuşulduğu ve bunlardan yüzlercesinin gelecek yüzyılda yok olma tehlikesiyle karşı karşıya olduğu belirtilmektedir.',3,2),
(tid,'inference','Küçük toplulukların dillerini koruma çabaları neden önemlidir?','["Yalnızca dilbilimcilerin akademik çalışmaları için değer taşır","Kültürel çeşitlilik ve benzersiz bilgi sistemlerinin yaşatılması için hayatidir","Dil kaybı herhangi bir sonuç doğurmaz","Küçük diller büyük dillere entegre edilmelidir"]',1,'Her dilin eşsiz kültürel bilgi, dünya görüşü ve ifade biçimleri taşıdığı; dolayısıyla bir dilin yok olmasının geri dönüşü olmayan kültürel bir kayıp anlamına geldiği metinden anlaşılmaktadır.',3,3);

END $$;
